unit Reports_Forms;

interface

uses
  SysUtils, Classes, Graphics, ppCtrls, ppBarCod, ppPrnabl, ppClass,
  ppCache, ppBands, ppProd, ppReport, ppDB, ppComm, ppRelatv, ppDBPipe,
  ppVar, ppModule, ppStrtch, ppSubRpt, ppChrt, ppChrtDP,
  ppParameter, myChkBox, ppMemo, RegKeys, JPeg;

type
  TReportsAndForms = class(TDataModule)
    PipeVencimientos: TppDBPipeline;
    Labels: TppReport;
    PipeProductos: TppDBPipeline;
    Empty: TppReport;
    ppDetailBand2: TppDetailBand;
    ppImage1: TppImage;
    ppLabel1: TppLabel;
    PipeDetalles_Compra: TppDBPipeline;
    ReporteProductos_Fabricante: TppReport;
    PipeReportes: TppDBPipeline;
    ppHeaderBand1: TppHeaderBand;
    ppDetailBand3: TppDetailBand;
    ppFooterBand1: TppFooterBand;
    ppTitleBand1: TppTitleBand;
    ppSystemVariable1: TppSystemVariable;
    ppSystemVariable2: TppSystemVariable;
    ppDBText1: TppDBText;
    ppLabel3: TppLabel;
    ppDBText5: TppDBText;
    ppLabel7: TppLabel;
    ppDBText12: TppDBText;
    ppLabel14: TppLabel;
    ppDBText15: TppDBText;
    ppLabel17: TppLabel;
    ppDBText28: TppDBText;
    ppLabel30: TppLabel;
    ppLine2: TppLine;
    Nombre_Siglas_Clientes: TppLabel;
    Direccion_Ciudad_Pais_Clientes: TppLabel;
    Telefono_Fax_Rnc_Clientes: TppLabel;
    Titulo: TppLabel;
    ppGroup1: TppGroup;
    CabezaGrupo: TppGroupHeaderBand;
    PieGrupo: TppGroupFooterBand;
    ppLine3: TppLine;
    ppLine4: TppLine;
    ppDBCalc1: TppDBCalc;
    IDCosto: TppLabel;
    ppLabel6: TppLabel;
    PipeFabricante: TppDBPipeline;
    LCostoPromedio: TppLabel;
    ppLabel11: TppLabel;
    CostoPromedio: TppVariable;
    PrecioContado: TppVariable;
    TCostoPromedio: TppVariable;
    TPrecioContado: TppVariable;
    ppLabel12: TppLabel;
    ppLabel16: TppLabel;
    ppLabel20: TppLabel;
    ppSummaryBand1: TppSummaryBand;
    ppDBCalc2: TppDBCalc;
    TGCostoPromedio: TppVariable;
    TGPrecioContado: TppVariable;
    ppLabel23: TppLabel;
    ppLabel24: TppLabel;
    ppLabel25: TppLabel;
    ppLabel28: TppLabel;
    Usuario: TppLabel;
    ppLine1: TppLine;
    ppLine5: TppLine;
    ppLabel4: TppLabel;
    ppLabel5: TppLabel;
    ppLabel8: TppLabel;
    ppLabel9: TppLabel;
    ppLabel13: TppLabel;
    ppLabel15: TppLabel;
    ppLabel32: TppLabel;
    ppLabel33: TppLabel;
    ppLabel34: TppLabel;
    Depto_Fabricante: TppLabel;
    Elemento_Fabricante: TppLabel;
    Status_Fabricante: TppLabel;
    Tipo_Fabricante: TppLabel;
    ReporteProductos_Proveedores: TppReport;
    ppTitleBand2: TppTitleBand;
    ppLabel35: TppLabel;
    ppLabel36: TppLabel;
    ppLabel37: TppLabel;
    ppHeaderBand2: TppHeaderBand;
    ppLabel38: TppLabel;
    ppLabel39: TppLabel;
    ppLabel40: TppLabel;
    ppLabel41: TppLabel;
    ppLabel42: TppLabel;
    ppLabel43: TppLabel;
    ppLabel44: TppLabel;
    ppLabel45: TppLabel;
    ppLabel46: TppLabel;
    Depto_Proveedor: TppLabel;
    Elemento_Proveedor: TppLabel;
    Status_Proveedor: TppLabel;
    Tipo_Proveedor: TppLabel;
    ppDetailBand4: TppDetailBand;
    ppDBText4: TppDBText;
    ppDBText6: TppDBText;
    ppDBText7: TppDBText;
    ppDBText8: TppDBText;
    ppDBText9: TppDBText;
    ppLabel51: TppLabel;
    ppLabel52: TppLabel;
    ppVariable1: TppVariable;
    ppVariable2: TppVariable;
    ppFooterBand2: TppFooterBand;
    ppLine6: TppLine;
    ppSystemVariable3: TppSystemVariable;
    ppSystemVariable4: TppSystemVariable;
    ppLabel53: TppLabel;
    ppSummaryBand2: TppSummaryBand;
    ppLine7: TppLine;
    ppDBCalc3: TppDBCalc;
    ppVariable3: TppVariable;
    ppVariable5: TppVariable;
    ppLabel54: TppLabel;
    ppLabel55: TppLabel;
    ppLabel56: TppLabel;
    ppLabel59: TppLabel;
    ppGroup2: TppGroup;
    ppGroupHeaderBand1: TppGroupHeaderBand;
    ppLine8: TppLine;
    ppLabel62: TppLabel;
    ppLabel63: TppLabel;
    ppLabel64: TppLabel;
    ppLabel65: TppLabel;
    ppLabel66: TppLabel;
    ppLine9: TppLine;
    ppLabel67: TppLabel;
    ppLabel68: TppLabel;
    ppGroupFooterBand1: TppGroupFooterBand;
    ppDBCalc4: TppDBCalc;
    ppVariable9: TppVariable;
    ppVariable11: TppVariable;
    ppLabel69: TppLabel;
    ppLabel70: TppLabel;
    ppLabel73: TppLabel;
    ppLine10: TppLine;
    ppLabel76: TppLabel;
    ppGroup3: TppGroup;
    ppGroupHeaderBand2: TppGroupHeaderBand;
    ppGroupFooterBand2: TppGroupFooterBand;
    PipeProveedor: TppDBPipeline;
    NombreFabricante_Proveedor: TppLabel;
    NombreProveedor: TppLabel;
    NombreFabricante: TppLabel;
    Nombre_Fabricante: TppLabel;
    Num_Fabricante: TppLabel;
    Num_Fabricante_Proveedor: TppLabel;
    Num_Proveedor: TppLabel;
    Nombre_Fabricante_Proveedor: TppLabel;
    Reporte_Vencimientos: TppReport;
    Pipe_Criterio_Vencimiento: TppDBPipeline;
    ppHeaderBand3: TppHeaderBand;
    ppDetailBand5: TppDetailBand;
    ppFooterBand3: TppFooterBand;
    ppTitleBand3: TppTitleBand;
    ppDBText2: TppDBText;
    ppDBText10: TppDBText;
    ppDBText11: TppDBText;
    ppDBText13: TppDBText;
    ppGroup4: TppGroup;
    ppGroupHeaderBand3: TppGroupHeaderBand;
    ppGroupFooterBand3: TppGroupFooterBand;
    ppDBCalc5: TppDBCalc;
    ppLabel18: TppLabel;
    ppLabel19: TppLabel;
    ppLabel27: TppLabel;
    ppLabel29: TppLabel;
    Clasificacion: TppLabel;
    ppLabel57: TppLabel;
    ppLine11: TppLine;
    ppLabel21: TppLabel;
    ppLabel26: TppLabel;
    MES: TppVariable;
    ppLine13: TppLine;
    Criterio: TppLabel;
    ppLine12: TppLine;
    ppSystemVariable5: TppSystemVariable;
    ppSystemVariable6: TppSystemVariable;
    ppLabel22: TppLabel;
    Reporte_Ventas_Ncf: TppReport;
    ppTitleBand4: TppTitleBand;
    ppHeaderBand4: TppHeaderBand;
    ppDetailBand6: TppDetailBand;
    ppDBText14: TppDBText;
    ppDBText16: TppDBText;
    ppDBText17: TppDBText;
    ppDBText18: TppDBText;
    ppDBText19: TppDBText;
    ppDBText20: TppDBText;
    ppDBText22: TppDBText;
    ppFooterBand4: TppFooterBand;
    ppLine14: TppLine;
    ppSystemVariable7: TppSystemVariable;
    ppSystemVariable8: TppSystemVariable;
    ppDBCalc6: TppDBCalc;
    Pagado: TppDBCalc;
    ppDBCalc7: TppDBCalc;
    TotalNeto: TppDBCalc;
    ppLabel31: TppLabel;
    ppLabel47: TppLabel;
    TotalEfectivo: TppVariable;
    ppLabel60: TppLabel;
    ppLabel61: TppLabel;
    TotaPagadoFact: TppVariable;
    ppLine15: TppLine;
    ppSummaryBand3: TppSummaryBand;
    ppGroup5: TppGroup;
    ppGroupHeaderBand4: TppGroupHeaderBand;
    ppLabel86: TppLabel;
    ppLabel87: TppLabel;
    ppLabel88: TppLabel;
    ppLabel89: TppLabel;
    ppLabel90: TppLabel;
    ppLabel91: TppLabel;
    ppLabel93: TppLabel;
    ppDBText34: TppDBText;
    ppLabel94: TppLabel;
    ppGroupFooterBand4: TppGroupFooterBand;
    ppDBCalc8: TppDBCalc;
    ppDBCalc9: TppDBCalc;
    ppDBCalc10: TppDBCalc;
    ppDBCalc11: TppDBCalc;
    ppLabel95: TppLabel;
    ppLabel96: TppLabel;
    ppLine19: TppLine;
    ppLabel101: TppLabel;
    ppDBText35: TppDBText;
    Pipe_Facturas: TppDBPipeline;
    ppLabel50: TppLabel;
    ppLabel58: TppLabel;
    ppLabel71: TppLabel;
    ClasificacionVentas: TppLabel;
    ppLabel75: TppLabel;
    InventarioVendido: TppReport;
    ppTitleBand5: TppTitleBand;
    ppLabel72: TppLabel;
    ppHeaderBand5: TppHeaderBand;
    ppLine16: TppLine;
    ppLine17: TppLine;
    ppLabel77: TppLabel;
    ppLabel78: TppLabel;
    ppLabel79: TppLabel;
    ppLabel80: TppLabel;
    ppLabel81: TppLabel;
    ppLabel82: TppLabel;
    ppLabel83: TppLabel;
    ppLabel84: TppLabel;
    DelAl: TppLabel;
    ppSystemVariable9: TppSystemVariable;
    ppDetailBand7: TppDetailBand;
    ppDBText23: TppDBText;
    ppDBText24: TppDBText;
    ppDBText25: TppDBText;
    ppDBText26: TppDBText;
    ppDBText27: TppDBText;
    ppDBText29: TppDBText;
    ppDBText30: TppDBText;
    ppDBText31: TppDBText;
    ppFooterBand5: TppFooterBand;
    ppLine20: TppLine;
    ppSystemVariable10: TppSystemVariable;
    TVenta: TppDBCalc;
    ppLabel85: TppLabel;
    ppLabel99: TppLabel;
    ppLabel100: TppLabel;
    ppLabel102: TppLabel;
    TCosto: TppDBCalc;
    Pipe_Mercancia_Vendida: TppDBPipeline;
    ppLabel103: TppLabel;
    ppLabel104: TppLabel;
    ppLabel105: TppLabel;
    ppLabel106: TppLabel;
    ppLabel107: TppLabel;
    Depto_Vendida: TppLabel;
    Producto_Vendida: TppLabel;
    ppLabel110: TppLabel;
    lProducto_Vendida: TppLabel;
    ppLabel113: TppLabel;
    ppLabel114: TppLabel;
    Usuario_Vendida: TppLabel;
    ppDBCalc12: TppDBCalc;
    PipeDetPagos: TppDBPipeline;
    PipeClientes: TppDBPipeline;
    PipePagos: TppDBPipeline;
    InventarioComprado: TppReport;
    ppTitleBand7: TppTitleBand;
    Titulo_Comprada: TppLabel;
    ppLabel129: TppLabel;
    ppLabel130: TppLabel;
    ppLabel131: TppLabel;
    ppHeaderBand7: TppHeaderBand;
    ppLine23: TppLine;
    ppLine24: TppLine;
    ppLabel132: TppLabel;
    ppLabel133: TppLabel;
    ppLabel134: TppLabel;
    ppLabel135: TppLabel;
    ppLabel137: TppLabel;
    ppLabel138: TppLabel;
    DelAlComprada: TppLabel;
    ppSystemVariable12: TppSystemVariable;
    ppLabel141: TppLabel;
    ppLabel142: TppLabel;
    Depto_Comprada: TppLabel;
    Producto_Comprada: TppLabel;
    ppLabel145: TppLabel;
    ppLabel146: TppLabel;
    ppLabel147: TppLabel;
    ppLabel148: TppLabel;
    Usuario_Comprada: TppLabel;
    ppDetailBand9: TppDetailBand;
    ppDBText42: TppDBText;
    ppDBText43: TppDBText;
    ppDBText44: TppDBText;
    ppDBText45: TppDBText;
    ppDBText46: TppDBText;
    ppDBText48: TppDBText;
    ppFooterBand7: TppFooterBand;
    ppLine25: TppLine;
    ppSystemVariable13: TppSystemVariable;
    ppLabel150: TppLabel;
    ppDBCalc14: TppDBCalc;
    Pipe_Mercancia_Comprada: TppDBPipeline;
    PipeSalida: TppDBPipeline;
    PipeDetalleSalida: TppDBPipeline;
    FormSalidaInventario: TppReport;
    PipeListadoClientes: TppDBPipeline;
    FormFactura: TppReport;
    PipeDetalleFacturas: TppDBPipeline;
    PipeFacturas: TppDBPipeline;
    FormCompra: TppReport;
    ppTitleBand9: TppTitleBand;
    ppShape3: TppShape;
    ppDBText80: TppDBText;
    ppDBText81: TppDBText;
    ppLabel178: TppLabel;
    ppDBText82: TppDBText;
    ppDBText83: TppDBText;
    ppLabel179: TppLabel;
    ppDBText84: TppDBText;
    ppLabel180: TppLabel;
    ppDBText85: TppDBText;
    ppLabel181: TppLabel;
    ppDBText86: TppDBText;
    ppLabel182: TppLabel;
    ppDBText87: TppDBText;
    ppLabel183: TppLabel;
    Logo_Compras: TppImage;
    ppLabel184: TppLabel;
    ppLabel185: TppLabel;
    ppLabel186: TppLabel;
    ppLabel187: TppLabel;
    ppLabel188: TppLabel;
    ppLabel190: TppLabel;
    ppLabel194: TppLabel;
    ppHeaderBand9: TppHeaderBand;
    ppShape4: TppShape;
    ppLabel195: TppLabel;
    ppLabel196: TppLabel;
    ppLabel197: TppLabel;
    ppLabel198: TppLabel;
    ppLabel199: TppLabel;
    ppLabel200: TppLabel;
    ppLabel201: TppLabel;
    ppDetailBand12: TppDetailBand;
    ppDBText88: TppDBText;
    ppDBText89: TppDBText;
    ppDBText90: TppDBText;
    ppDBText92: TppDBText;
    ppDBText93: TppDBText;
    ppDBText95: TppDBText;
    ppDBText96: TppDBText;
    ppFooterBand9: TppFooterBand;
    ppLine32: TppLine;
    ppSystemVariable18: TppSystemVariable;
    ppSystemVariable19: TppSystemVariable;
    ppLabel202: TppLabel;
    ppDBText97: TppDBText;
    Product_InvoicePendingLabel: TppLabel;
    Product_InvoicePendingAmmount: TppDBText;
    Product_InvoiceTaxLabel: TppLabel;
    Product_InvoiceTax: TppDBText;
    Product_InvoiceDiscountLabel: TppLabel;
    Product_InvoiceDiscount: TppDBText;
    ppLabel206: TppLabel;
    ppDBText101: TppDBText;
    ppLine33: TppLine;
    ppLabel207: TppLabel;
    ppLine34: TppLine;
    ppLabel208: TppLabel;
    Product_InvoicePaidLabel: TppLabel;
    Product_InvoicePaidAmmount: TppDBText;
    ppDBText103: TppDBText;
    ppLine37: TppLine;
    PipeDetalleCompras: TppDBPipeline;
    PipeCompras: TppDBPipeline;
    FormEstadisticaProducto: TppReport;
    ppHeaderBand10: TppHeaderBand;
    ppDetailBand13: TppDetailBand;
    ppFooterBand10: TppFooterBand;
    ppTitleBand10: TppTitleBand;
    ppSystemVariable20: TppSystemVariable;
    ppSystemVariable21: TppSystemVariable;
    ppDBText98: TppDBText;
    ppLabel204: TppLabel;
    ppDBText99: TppDBText;
    ppLabel205: TppLabel;
    ppDBText100: TppDBText;
    ppLabel209: TppLabel;
    ppDBText102: TppDBText;
    ppLabel210: TppLabel;
    ppDBText104: TppDBText;
    ppLabel211: TppLabel;
    ppDBText105: TppDBText;
    ppDBText107: TppDBText;
    ppLabel214: TppLabel;
    ppDBText108: TppDBText;
    ppLabel215: TppLabel;
    ppDBText109: TppDBText;
    ppLabel216: TppLabel;
    ppDBText110: TppDBText;
    ppLabel217: TppLabel;
    ppDBText111: TppDBText;
    ppLabel218: TppLabel;
    ppDBText112: TppDBText;
    ppLabel219: TppLabel;
    ppDBText113: TppDBText;
    ppLabel220: TppLabel;
    ppDBText114: TppDBText;
    ppLabel221: TppLabel;
    ppDBText115: TppDBText;
    ppLabel222: TppLabel;
    ppDBText117: TppDBText;
    ppLabel224: TppLabel;
    ppDBText118: TppDBText;
    ppLabel225: TppLabel;
    ppDBText121: TppDBText;
    ppLabel228: TppLabel;
    ppDBText122: TppDBText;
    ppLabel229: TppLabel;
    ppDBText123: TppDBText;
    ppLabel230: TppLabel;
    ppDBText124: TppDBText;
    ppLabel231: TppLabel;
    ppDBText125: TppDBText;
    ppLabel232: TppLabel;
    ppDBText126: TppDBText;
    ppLabel233: TppLabel;
    ppLabel234: TppLabel;
    ppLabel235: TppLabel;
    ppLabel236: TppLabel;
    ppLabel237: TppLabel;
    ppDBText131: TppDBText;
    ppLabel238: TppLabel;
    ppDBText132: TppDBText;
    ppLabel239: TppLabel;
    ppDBText133: TppDBText;
    ppLabel240: TppLabel;
    ppDBText134: TppDBText;
    ppLabel241: TppLabel;
    ppDBText135: TppDBText;
    ppLabel242: TppLabel;
    ppDBText136: TppDBText;
    ppLabel243: TppLabel;
    ppDBText137: TppDBText;
    ppLabel244: TppLabel;
    ppLabel203: TppLabel;
    ppLine39: TppLine;
    ppLine41: TppLine;
    ppLabel212: TppLabel;
    myDBCheckBox1: TmyDBCheckBox;
    myDBCheckBox2: TmyDBCheckBox;
    myDBCheckBox3: TmyDBCheckBox;
    myDBCheckBox4: TmyDBCheckBox;
    ppLabel223: TppLabel;
    ppLine42: TppLine;
    ppLabel226: TppLabel;
    ppLine43: TppLine;
    ppLabel213: TppLabel;
    ppDBText106: TppDBText;
    Movimientos: TppTeeChart;
    RptEfectivo: TppSubReport;
    ppChildReport2: TppChildReport;
    ppTitleBand11: TppTitleBand;
    ppLine44: TppLine;
    ppLabel227: TppLabel;
    ppLabel245: TppLabel;
    ppLabel246: TppLabel;
    ppLabel247: TppLabel;
    ppLabel248: TppLabel;
    ppDetailBand14: TppDetailBand;
    ppDBText116: TppDBText;
    ppDBText119: TppDBText;
    ppDBText120: TppDBText;
    ppDBText127: TppDBText;
    RptPagos: TppSubReport;
    ppChildReport1: TppChildReport;
    ppTitleBand12: TppTitleBand;
    ppLine45: TppLine;
    ppLabel250: TppLabel;
    ppLabel251: TppLabel;
    ppLabel252: TppLabel;
    ppLabel253: TppLabel;
    ppLabel254: TppLabel;
    ppDetailBand15: TppDetailBand;
    ppDBText129: TppDBText;
    ppDBText130: TppDBText;
    ppDBText138: TppDBText;
    ppDBText139: TppDBText;
    ppSummaryBand5: TppSummaryBand;
    TotalPagos: TppDBCalc;
    ppLabel256: TppLabel;
    PipeDesgloceEfectivo: TppDBPipeline;
    PipeListadoPagos: TppDBPipeline;
    ppSummaryBand6: TppSummaryBand;
    ppLabel249: TppLabel;
    ppDBCalc13: TppDBCalc;
    ppLine46: TppLine;
    ppLine47: TppLine;
    ppLine40: TppLine;
    ppDBText128: TppDBText;
    ppDBText140: TppDBText;
    ppDBText141: TppDBText;
    ppDBText142: TppDBText;
    ppLabel255: TppLabel;
    ppDBText143: TppDBText;
    ppDBText144: TppDBText;
    ppDBText145: TppDBText;
    ppLabel257: TppLabel;
    ppLabel258: TppLabel;
    ppLabel262: TppLabel;
    ppLabel263: TppLabel;
    ppLabel264: TppLabel;
    ppLabel265: TppLabel;
    ppDBText146: TppDBText;
    ppLabel259: TppLabel;
    ppDBText147: TppDBText;
    ppLabel260: TppLabel;
    ppLabel266: TppLabel;
    ppDBText149: TppDBText;
    ppDBText148: TppDBText;
    ppLabel261: TppLabel;
    ppDBText150: TppDBText;
    ppLabel267: TppLabel;
    ppLabel268: TppLabel;
    ppDBText151: TppDBText;
    ppDBText152: TppDBText;
    ppLabel269: TppLabel;
    ppDBText153: TppDBText;
    ppLabel270: TppLabel;
    ppLabel271: TppLabel;
    ppDBText154: TppDBText;
    ppLabel272: TppLabel;
    ppDBText155: TppDBText;
    ppLabel273: TppLabel;
    ppDBText156: TppDBText;
    ppDBText157: TppDBText;
    ppLabel274: TppLabel;
    ppDBText158: TppDBText;
    ppLabel275: TppLabel;
    ppLabel276: TppLabel;
    ppDBText159: TppDBText;
    Recibo_Nota_Credito: TppReport;
    ppTitleBand13: TppTitleBand;
    ppHeaderBand11: TppHeaderBand;
    ppLabel279: TppLabel;
    ppDBText160: TppDBText;
    ppLabel280: TppLabel;
    ppLabel281: TppLabel;
    ppLabel282: TppLabel;
    ppLabel283: TppLabel;
    ppLabel284: TppLabel;
    ppDBText161: TppDBText;
    ppDBText162: TppDBText;
    ppLabel285: TppLabel;
    ppDBText163: TppDBText;
    ppLabel286: TppLabel;
    ppLabel287: TppLabel;
    ppLabel288: TppLabel;
    ppLabel289: TppLabel;
    ppLabel290: TppLabel;
    ppDetailBand16: TppDetailBand;
    ppDBText164: TppDBText;
    ppDBText165: TppDBText;
    ppFooterBand11: TppFooterBand;
    ppSystemVariable22: TppSystemVariable;
    ppLabel293: TppLabel;
    ppLine38: TppLine;
    ppLine48: TppLine;
    ppLabel294: TppLabel;
    ppSummaryBand7: TppSummaryBand;
    ppLabel295: TppLabel;
    ppDBText167: TppDBText;
    PipeNotas_Credito: TppDBPipeline;
    PipeDetalle_Notas_Credito: TppDBPipeline;
    Estado_Cuenta_Clientes: TppReport;
    ppTitleBand14: TppTitleBand;
    ppLabel297: TppLabel;
    ppDetailBand17: TppDetailBand;
    ppShape5: TppShape;
    ppDBText176: TppDBText;
    ppDBText177: TppDBText;
    ppDBText178: TppDBText;
    ppDBText179: TppDBText;
    ppDBText183: TppDBText;
    ppDBText184: TppDBText;
    Pagos: TppSubReport;
    ppChildReport4: TppChildReport;
    ppTitleBand16: TppTitleBand;
    ppLabel308: TppLabel;
    ppShape7: TppShape;
    ppLabel309: TppLabel;
    ppLabel310: TppLabel;
    ppLabel311: TppLabel;
    ppDetailBand19: TppDetailBand;
    ppDBText186: TppDBText;
    ppDBText187: TppDBText;
    ppDBText190: TppDBText;
    ppSummaryBand9: TppSummaryBand;
    ppDBCalc17: TppDBCalc;
    ppLabel314: TppLabel;
    ppLabel315: TppLabel;
    ppLabel316: TppLabel;
    ppLabel317: TppLabel;
    ppLabel318: TppLabel;
    ppLabel322: TppLabel;
    ppLabel323: TppLabel;
    ppFooterBand12: TppFooterBand;
    ppLine49: TppLine;
    ppSystemVariable23: TppSystemVariable;
    ppSystemVariable24: TppSystemVariable;
    ppSummaryBand10: TppSummaryBand;
    ppShape9: TppShape;
    ppDBText196: TppDBText;
    ppDBText197: TppDBText;
    ppLabel298: TppLabel;
    ppDBText198: TppDBText;
    ppDBText199: TppDBText;
    ppImage2: TppImage;
    ppLabel330: TppLabel;
    ppLabel331: TppLabel;
    ppLabel332: TppLabel;
    Notas_Credito: TppSubReport;
    ppChildReport3: TppChildReport;
    ppTitleBand15: TppTitleBand;
    ppLabel299: TppLabel;
    ppShape6: TppShape;
    ppLabel300: TppLabel;
    ppLabel301: TppLabel;
    ppLabel302: TppLabel;
    ppDetailBand18: TppDetailBand;
    ppDBText169: TppDBText;
    ppDBText170: TppDBText;
    ppDBText173: TppDBText;
    ppSummaryBand8: TppSummaryBand;
    ppDBCalc15: TppDBCalc;
    ppLabel305: TppLabel;
    Pipe_Facturas_Cliente: TppDBPipeline;
    ppDBText174: TppDBText;
    ppLabel306: TppLabel;
    ppShape8: TppShape;
    ppLabel307: TppLabel;
    ppDBText175: TppDBText;
    ppDBCalc16: TppDBCalc;
    ppDBCalc18: TppDBCalc;
    ppDBCalc19: TppDBCalc;
    Pipe_Pagos_Cliente: TppDBPipeline;
    Pipe_Notas_Credito_Cliente: TppDBPipeline;
    FormOrdenCompra: TppReport;
    ppTitleBand17: TppTitleBand;
    ppShape10: TppShape;
    ppDBText171: TppDBText;
    ppDBText172: TppDBText;
    ppLabel312: TppLabel;
    ppDBText180: TppDBText;
    ppDBText181: TppDBText;
    ppLabel313: TppLabel;
    ppDBText182: TppDBText;
    ppLabel319: TppLabel;
    ppDBText185: TppDBText;
    ppLabel324: TppLabel;
    ppImage3: TppImage;
    ppLabel325: TppLabel;
    ppLabel326: TppLabel;
    ppLabel327: TppLabel;
    ppLabel328: TppLabel;
    ppLabel329: TppLabel;
    ppHeaderBand12: TppHeaderBand;
    ppShape11: TppShape;
    ppLabel335: TppLabel;
    ppLabel336: TppLabel;
    ppLabel337: TppLabel;
    ppLabel339: TppLabel;
    ppDetailBand20: TppDetailBand;
    ppDBText191: TppDBText;
    ppDBText192: TppDBText;
    ppDBText193: TppDBText;
    ppDBText195: TppDBText;
    ppFooterBand13: TppFooterBand;
    ppLine50: TppLine;
    ppSystemVariable25: TppSystemVariable;
    ppSystemVariable26: TppSystemVariable;
    ppLine51: TppLine;
    ppLabel347: TppLabel;
    ppLine52: TppLine;
    ppLabel348: TppLabel;
    PipeDetalleOrdenCompras: TppDBPipeline;
    PipeOrdenCompra: TppDBPipeline;
    ppSummaryBand11: TppSummaryBand;
    ppLine53: TppLine;
    ppLabel320: TppLabel;
    ppDBMemo1: TppDBMemo;
    ppLabel321: TppLabel;
    ppSummaryBand13: TppSummaryBand;
    ppLine55: TppLine;
    ppLabel338: TppLabel;
    ppDBMemo3: TppDBMemo;
    ppLabel340: TppLabel;
    ppParameterList1: TppParameterList;
    ppDetailBand1: TppDetailBand;
    Descripcion_Etiqueta: TppDBText;
    Nombre_Comp: TppLabel;
    ppDBText3: TppDBText;
    ppLabel342: TppLabel;
    ppDBText69: TppDBText;
    ppDBCalc20: TppDBCalc;
    ppDBCalc21: TppDBCalc;
    ppLine56: TppLine;
    ppLine57: TppLine;
    ppDBCalc22: TppDBCalc;
    ppDBCalc23: TppDBCalc;
    ReporteNCF: TppReport;
    ppTitleBand18: TppTitleBand;
    ppLabel343: TppLabel;
    ppLabel350: TppLabel;
    ppLabel351: TppLabel;
    ppHeaderBand13: TppHeaderBand;
    ClasificacionNCF: TppLabel;
    ppLabel353: TppLabel;
    ppDetailBand21: TppDetailBand;
    ppDBText194: TppDBText;
    ppDBText200: TppDBText;
    ppDBText201: TppDBText;
    ppDBText202: TppDBText;
    ppDBText203: TppDBText;
    ppDBText204: TppDBText;
    ppDBText205: TppDBText;
    ppDBText206: TppDBText;
    ppLabel354: TppLabel;
    ppLabel355: TppLabel;
    ppDBText207: TppDBText;
    ppDBText208: TppDBText;
    ppFooterBand14: TppFooterBand;
    ppLine58: TppLine;
    ppSystemVariable27: TppSystemVariable;
    ppSystemVariable28: TppSystemVariable;
    ppDBCalc24: TppDBCalc;
    ppDBCalc25: TppDBCalc;
    ppDBCalc26: TppDBCalc;
    ppDBCalc27: TppDBCalc;
    ppLabel356: TppLabel;
    ppLabel357: TppLabel;
    ppLabel358: TppLabel;
    ppLabel359: TppLabel;
    ppLabel362: TppLabel;
    ppDBCalc28: TppDBCalc;
    ppLine60: TppLine;
    ppLabel363: TppLabel;
    ppDBCalc29: TppDBCalc;
    ppSummaryBand14: TppSummaryBand;
    ppGroup6: TppGroup;
    ppGroupHeaderBand5: TppGroupHeaderBand;
    ppLine65: TppLine;
    ppLabel376: TppLabel;
    ppLabel377: TppLabel;
    ppLabel378: TppLabel;
    ppLabel379: TppLabel;
    ppLabel380: TppLabel;
    ppLabel381: TppLabel;
    ppDBText217: TppDBText;
    ppLabel382: TppLabel;
    ppLabel383: TppLabel;
    ppGroupFooterBand5: TppGroupFooterBand;
    ppDBCalc32: TppDBCalc;
    ppDBCalc33: TppDBCalc;
    ppDBCalc34: TppDBCalc;
    ppDBCalc35: TppDBCalc;
    ppLabel384: TppLabel;
    ppLabel385: TppLabel;
    ppLabel386: TppLabel;
    ppLabel387: TppLabel;
    ppLine66: TppLine;
    ppLabel388: TppLabel;
    ppDBText218: TppDBText;
    ppDBCalc36: TppDBCalc;
    ppLabel389: TppLabel;
    ppLine67: TppLine;
    ppDBCalc37: TppDBCalc;
    ppLabel390: TppLabel;
    ppDBText209: TppDBText;
    ppDBText210: TppDBText;
    ppDBText213: TppDBText;
    ppLabel126: TppLabel;
    ppLabel352: TppLabel;
    ppLabel360: TppLabel;
    ppLabel361: TppLabel;
    ppLine61: TppLine;
    ppLine62: TppLine;
    ppLabel292: TppLabel;
    ppDBText214: TppDBText;
    ppImage4: TppImage;
    ppLabel2: TppLabel;
    ppLabel277: TppLabel;
    ppLabel278: TppLabel;
    ReporteProductos_Categoria: TppReport;
    ppTitleBand19: TppTitleBand;
    ppLabel365: TppLabel;
    ppLabel366: TppLabel;
    ppLabel367: TppLabel;
    ppHeaderBand14: TppHeaderBand;
    Titulo_Categoria: TppLabel;
    ppLabel369: TppLabel;
    ppLabel370: TppLabel;
    ppLabel371: TppLabel;
    ppLabel372: TppLabel;
    ppLabel373: TppLabel;
    ppLabel374: TppLabel;
    ppLabel375: TppLabel;
    ppLabel391: TppLabel;
    Depto_Categoria: TppLabel;
    Elemento_Categoria: TppLabel;
    Status_Categoria: TppLabel;
    Tipo_Categoria: TppLabel;
    ppDetailBand22: TppDetailBand;
    ppDBText216: TppDBText;
    ppDBText219: TppDBText;
    ppDBText220: TppDBText;
    ppDBText221: TppDBText;
    ppDBText222: TppDBText;
    ppLabel396: TppLabel;
    ppLabel397: TppLabel;
    ppVariable4: TppVariable;
    ppVariable6: TppVariable;
    ppFooterBand15: TppFooterBand;
    ppLine63: TppLine;
    ppSystemVariable29: TppSystemVariable;
    ppSystemVariable30: TppSystemVariable;
    ppLabel398: TppLabel;
    ppSummaryBand15: TppSummaryBand;
    ppLine64: TppLine;
    ppDBCalc30: TppDBCalc;
    TGCostoPromedio_Categoria: TppVariable;
    TGPrecioContado_Categoria: TppVariable;
    ppLabel399: TppLabel;
    ppLabel400: TppLabel;
    ppLabel401: TppLabel;
    ppLabel402: TppLabel;
    grpProductos_Categorias: TppGroup;
    ppGroupHeaderBand6: TppGroupHeaderBand;
    ppLine68: TppLine;
    ppLabel403: TppLabel;
    ppLabel404: TppLabel;
    ppLabel405: TppLabel;
    ppLabel406: TppLabel;
    ppLabel407: TppLabel;
    ppLine69: TppLine;
    ppLabel408: TppLabel;
    ppLabel409: TppLabel;
    NombreCategoria: TppLabel;
    Num_Categoria: TppLabel;
    SubTotales_Productos_Categorias: TppGroupFooterBand;
    ppLine70: TppLine;
    ppLabel415: TppLabel;
    ppParameterList2: TppParameterList;
    Codigo_Etiqueta: TppBarCode;
    ReciboPagoCliente: TppReport;
    ppTitleBand20: TppTitleBand;
    ppImage5: TppImage;
    ppLabel393: TppLabel;
    ppLabel394: TppLabel;
    ppLabel395: TppLabel;
    ppHeaderBand15: TppHeaderBand;
    ppLabel410: TppLabel;
    ppDBText224: TppDBText;
    ppLabel411: TppLabel;
    ppLabel416: TppLabel;
    ppLabel417: TppLabel;
    ppLabel418: TppLabel;
    ppLabel419: TppLabel;
    ppDBText225: TppDBText;
    ppDBText226: TppDBText;
    ppLabel420: TppLabel;
    ppLabel421: TppLabel;
    ppLabel422: TppLabel;
    ppLabel423: TppLabel;
    ppLabel424: TppLabel;
    ppLabel425: TppLabel;
    ppLabel426: TppLabel;
    ppLine71: TppLine;
    ppLabel427: TppLabel;
    ppDBText227: TppDBText;
    Status_Recibo_Pago: TppDBText;
    ppLabel428: TppLabel;
    ppLabel429: TppLabel;
    ppLabel430: TppLabel;
    ppLabel431: TppLabel;
    ppColumnHeaderBand3: TppColumnHeaderBand;
    ppDetailBand23: TppDetailBand;
    ppDBText228: TppDBText;
    ppDBText229: TppDBText;
    ppDBText230: TppDBText;
    ppDBText231: TppDBText;
    ppDBText232: TppDBText;
    ppDBText233: TppDBText;
    ppColumnFooterBand3: TppColumnFooterBand;
    ppFooterBand16: TppFooterBand;
    ppLine72: TppLine;
    ppSystemVariable31: TppSystemVariable;
    ppLabel432: TppLabel;
    ppLine73: TppLine;
    ppLabel433: TppLabel;
    ppSummaryBand16: TppSummaryBand;
    ppLabel434: TppLabel;
    ppDBText234: TppDBText;
    ppLine74: TppLine;
    ppDBCalc38: TppDBCalc;
    ppDBCalc39: TppDBCalc;
    ppDBCalc40: TppDBCalc;
    ppDBCalc41: TppDBCalc;
    ppDBText32: TppDBText;
    ppLabel74: TppLabel;
    ppDBText33: TppDBText;
    ppLabel108: TppLabel;
    ppDBText36: TppDBText;
    ppLabel109: TppLabel;
    Status_Nota_Credito: TppDBText;
    ppDBText38: TppDBText;
    ppDBText39: TppDBText;
    ppLabel111: TppLabel;
    ppLine21: TppLine;
    ppDBText40: TppDBText;
    ppDBText37: TppDBText;
    ppLabel112: TppLabel;
    ppDBText41: TppDBText;
    ppLabel115: TppLabel;
    ppLabel92: TppLabel;
    ppDBText166: TppDBText;
    ppShape12: TppShape;
    ppLabel97: TppLabel;
    ppLabel98: TppLabel;
    ppLabel345: TppLabel;
    ppLabel346: TppLabel;
    ppLabel48: TppLabel;
    ppLabel49: TppLabel;
    ppLabel116: TppLabel;
    ppLabel117: TppLabel;
    ReporteClientes: TppReport;
    ppTitleBand6: TppTitleBand;
    TitClientes: TppLabel;
    ppImage6: TppImage;
    ppLabel118: TppLabel;
    ppLabel119: TppLabel;
    ppLabel120: TppLabel;
    ppDBText21: TppDBText;
    ppHeaderBand6: TppHeaderBand;
    ppShape13: TppShape;
    ppLabel121: TppLabel;
    ppLabel122: TppLabel;
    ppLabel123: TppLabel;
    ppLabel124: TppLabel;
    ppLabel125: TppLabel;
    ppLabel127: TppLabel;
    ppDetailBand8: TppDetailBand;
    ppDBText189: TppDBText;
    ppDBText212: TppDBText;
    ppDBText235: TppDBText;
    ppDBText236: TppDBText;
    ppDBText237: TppDBText;
    ppDBText238: TppDBText;
    ppFooterBand6: TppFooterBand;
    ppLine18: TppLine;
    ppSystemVariable11: TppSystemVariable;
    ppSystemVariable32: TppSystemVariable;
    ppGroup8: TppGroup;
    ppGroupHeaderBand7: TppGroupHeaderBand;
    ppShape14: TppShape;
    ppDBText239: TppDBText;
    ppGroupFooterBand7: TppGroupFooterBand;
    ReportePagos: TppReport;
    ppTitleBand21: TppTitleBand;
    TitPagos: TppLabel;
    ppImage8: TppImage;
    ppLabel291: TppLabel;
    ppLabel344: TppLabel;
    ppLabel349: TppLabel;
    ppHeaderBand16: TppHeaderBand;
    ppShape15: TppShape;
    ppLabel435: TppLabel;
    ppLabel436: TppLabel;
    ppLabel437: TppLabel;
    ppLabel438: TppLabel;
    ppLabel439: TppLabel;
    ppLabel440: TppLabel;
    ppLabel441: TppLabel;
    ppLabel442: TppLabel;
    ppDetailBand24: TppDetailBand;
    ppDBText240: TppDBText;
    ppDBText241: TppDBText;
    ppDBText242: TppDBText;
    ppDBText243: TppDBText;
    ppDBText244: TppDBText;
    ppDBText245: TppDBText;
    Cliente_Pagos: TppVariable;
    ppDBText246: TppDBText;
    ppFooterBand17: TppFooterBand;
    ppLine22: TppLine;
    ppLine59: TppLine;
    ppSystemVariable33: TppSystemVariable;
    ppDBCalc42: TppDBCalc;
    ppLabel443: TppLabel;
    ppDBCalc43: TppDBCalc;
    ppDBCalc44: TppDBCalc;
    ppDBCalc45: TppDBCalc;
    ppLabel444: TppLabel;
    ppLabel445: TppLabel;
    ppLine75: TppLine;
    ppLine76: TppLine;
    ppLabel446: TppLabel;
    ppLabel447: TppLabel;
    ppLabel448: TppLabel;
    ppSystemVariable34: TppSystemVariable;
    Comprobante_Nota_Debito: TppReport;
    ppTitleBand22: TppTitleBand;
    ppImage10: TppImage;
    ppLabel449: TppLabel;
    ppLabel450: TppLabel;
    ppLabel451: TppLabel;
    ppHeaderBand17: TppHeaderBand;
    ppLabel452: TppLabel;
    ppDBText247: TppDBText;
    ppLabel453: TppLabel;
    ppLabel454: TppLabel;
    ppLabel455: TppLabel;
    ppLabel456: TppLabel;
    ppLabel457: TppLabel;
    ppDBText248: TppDBText;
    ppDBText249: TppDBText;
    ppLabel458: TppLabel;
    ppLabel459: TppLabel;
    ppLabel460: TppLabel;
    ppLabel461: TppLabel;
    ppLabel462: TppLabel;
    ppLabel463: TppLabel;
    ppLabel464: TppLabel;
    ppLabel465: TppLabel;
    ppLabel466: TppLabel;
    ppDBText250: TppDBText;
    ppLabel467: TppLabel;
    ppLabel468: TppLabel;
    ppLabel469: TppLabel;
    ppLine77: TppLine;
    ppColumnHeaderBand1: TppColumnHeaderBand;
    ppDetailBand25: TppDetailBand;
    ppDBText251: TppDBText;
    ppDBText252: TppDBText;
    ppDBText253: TppDBText;
    ppDBText254: TppDBText;
    ppDBText255: TppDBText;
    ppDBText256: TppDBText;
    ppColumnFooterBand1: TppColumnFooterBand;
    ppFooterBand18: TppFooterBand;
    ppLine78: TppLine;
    ppSystemVariable35: TppSystemVariable;
    ppLabel470: TppLabel;
    ppLine79: TppLine;
    ppLabel471: TppLabel;
    ppLine80: TppLine;
    ShadeAnuladosPagosVentas: TppShape;
    ppDBText257: TppDBText;
    ppLabel472: TppLabel;
    ppDBCalc46: TppDBCalc;
    ppLabel473: TppLabel;
    ShadeAnuladosReportePagos: TppShape;
    Cod_Generado: TppDBText;
    Reporte_Facturas: TppReport;
    Form_Seriales_Compra: TppReport;
    ppTitleBand26: TppTitleBand;
    ppShape18: TppShape;
    ppDBText279: TppDBText;
    ppDBText280: TppDBText;
    ppLabel518: TppLabel;
    ppDBText281: TppDBText;
    ppDBText282: TppDBText;
    ppLabel519: TppLabel;
    ppDBText283: TppDBText;
    ppLabel520: TppLabel;
    ppDBText284: TppDBText;
    ppLabel521: TppLabel;
    ppDBText285: TppDBText;
    ppLabel522: TppLabel;
    ppDBText286: TppDBText;
    ppLabel523: TppLabel;
    ppImage7: TppImage;
    ppLabel524: TppLabel;
    ppLabel525: TppLabel;
    ppLabel526: TppLabel;
    ppLabel527: TppLabel;
    ppLabel528: TppLabel;
    ppLabel529: TppLabel;
    ppLabel530: TppLabel;
    ppHeaderBand19: TppHeaderBand;
    ppShape19: TppShape;
    ppLabel531: TppLabel;
    ppLabel532: TppLabel;
    ppLabel533: TppLabel;
    ppLabel536: TppLabel;
    ppDetailBand29: TppDetailBand;
    ppDBText287: TppDBText;
    ppDBText288: TppDBText;
    ppDBText289: TppDBText;
    ppDBText292: TppDBText;
    ppFooterBand20: TppFooterBand;
    ppLine90: TppLine;
    ppSystemVariable38: TppSystemVariable;
    ppLabel538: TppLabel;
    ppDBText294: TppDBText;
    ppLabel542: TppLabel;
    ppDBText298: TppDBText;
    ppLine91: TppLine;
    ppLabel543: TppLabel;
    ppLine92: TppLine;
    ppLabel544: TppLabel;
    ppLine93: TppLine;
    ppSummaryBand19: TppSummaryBand;
    ppLine94: TppLine;
    ppLabel546: TppLabel;
    ppDBMemo4: TppDBMemo;
    ppLabel547: TppLabel;
    PipeSeriales_Compra: TppDBPipeline;
    Detalle_Seriales_Compra: TppSubReport;
    ppChildReport7: TppChildReport;
    ppDetailBand30: TppDetailBand;
    ppTitleBand27: TppTitleBand;
    ppLabel534: TppLabel;
    ppLine95: TppLine;
    ppColumnHeaderBand4: TppColumnHeaderBand;
    ppColumnFooterBand4: TppColumnFooterBand;
    ppDBText290: TppDBText;
    ppShape21: TppShape;
    ppLine96: TppLine;
    ppSystemVariable39: TppSystemVariable;
    PipeSeriales_Factura: TppDBPipeline;
    Reporte_Ventas_Cliente: TppReport;
    ppTitleBand29: TppTitleBand;
    ppLabel539: TppLabel;
    ppLabel540: TppLabel;
    ppLabel541: TppLabel;
    ppHeaderBand20: TppHeaderBand;
    Clasificacion_Vt_Cliente: TppLabel;
    ppLabel548: TppLabel;
    ppDetailBand32: TppDetailBand;
    ppDBText295: TppDBText;
    ppDBText296: TppDBText;
    ppDBText299: TppDBText;
    ppDBText300: TppDBText;
    ppDBText301: TppDBText;
    ppDBText302: TppDBText;
    ppDBText303: TppDBText;
    ppDBText304: TppDBText;
    ppDBText305: TppDBText;
    ppFooterBand21: TppFooterBand;
    ppDBCalc61: TppDBCalc;
    ppLine100: TppLine;
    ppSystemVariable40: TppSystemVariable;
    ppSystemVariable41: TppSystemVariable;
    ppDBCalc62: TppDBCalc;
    ppDBCalc63: TppDBCalc;
    ppDBCalc64: TppDBCalc;
    ppDBCalc65: TppDBCalc;
    ppLabel549: TppLabel;
    ppLabel550: TppLabel;
    ppLine102: TppLine;
    ppDBCalc66: TppDBCalc;
    ppLabel553: TppLabel;
    ppLabel554: TppLabel;
    ppLabel555: TppLabel;
    ppLabel556: TppLabel;
    ppSummaryBand20: TppSummaryBand;
    ppSubReport5: TppSubReport;
    ppChildReport10: TppChildReport;
    ppTitleBand31: TppTitleBand;
    ppLine105: TppLine;
    ppLabel564: TppLabel;
    ppLabel565: TppLabel;
    ppLabel566: TppLabel;
    ppLabel567: TppLabel;
    ppLabel568: TppLabel;
    ppDetailBand34: TppDetailBand;
    ppDBText311: TppDBText;
    ppDBText312: TppDBText;
    ppDBText313: TppDBText;
    ppDBText314: TppDBText;
    ppSummaryBand22: TppSummaryBand;
    ppLabel569: TppLabel;
    ppDBCalc68: TppDBCalc;
    ppLine106: TppLine;
    ppGroup10: TppGroup;
    ppGroupHeaderBand9: TppGroupHeaderBand;
    ppShape22: TppShape;
    ppLabel570: TppLabel;
    ppLabel571: TppLabel;
    ppLabel573: TppLabel;
    ppLabel574: TppLabel;
    ppDBText315: TppDBText;
    ppLabel575: TppLabel;
    ppLabel576: TppLabel;
    ppLabel577: TppLabel;
    ppLabel578: TppLabel;
    ppLabel579: TppLabel;
    ppLabel580: TppLabel;
    ppGroupFooterBand9: TppGroupFooterBand;
    ppLine107: TppLine;
    ppLine108: TppLine;
    ppDBCalc69: TppDBCalc;
    ppDBCalc70: TppDBCalc;
    ppDBCalc71: TppDBCalc;
    ppDBCalc72: TppDBCalc;
    ppLabel581: TppLabel;
    ppLabel582: TppLabel;
    ppLabel583: TppLabel;
    ppDBText316: TppDBText;
    ppDBCalc73: TppDBCalc;
    ppDBCalc74: TppDBCalc;
    ppLabel584: TppLabel;
    ppLabel585: TppLabel;
    ppLabel586: TppLabel;
    ppLabel587: TppLabel;
    ppParameterList3: TppParameterList;
    ppTitleBand8: TppTitleBand;
    ppShape1: TppShape;
    ppDBText47: TppDBText;
    ppDBText49: TppDBText;
    ppLabel10: TppLabel;
    ppDBText50: TppDBText;
    ppDBText51: TppDBText;
    ppLabel128: TppLabel;
    ppDBText52: TppDBText;
    ppLabel136: TppLabel;
    ppDBText53: TppDBText;
    ppLabel140: TppLabel;
    ppDBText55: TppDBText;
    ppLabel143: TppLabel;
    ppLabel144: TppLabel;
    ppLabel149: TppLabel;
    ppLabel152: TppLabel;
    ppLabel172: TppLabel;
    ppDBText58: TppDBText;
    ppLabel174: TppLabel;
    ppHeaderBand8: TppHeaderBand;
    ppShape20: TppShape;
    ppLabel175: TppLabel;
    ppLabel545: TppLabel;
    ppLabel551: TppLabel;
    ppLabel558: TppLabel;
    ppLabel559: TppLabel;
    ppDetailBand10: TppDetailBand;
    ppDBText62: TppDBText;
    ppDBText76: TppDBText;
    ppDBText79: TppDBText;
    ppDBText307: TppDBText;
    ppDBText308: TppDBText;
    ppSubReport4: TppSubReport;
    ppChildReport9: TppChildReport;
    ppTitleBand30: TppTitleBand;
    ppLine26: TppLine;
    ppLabel560: TppLabel;
    ppColumnHeaderBand6: TppColumnHeaderBand;
    ppDetailBand33: TppDetailBand;
    ppDBText309: TppDBText;
    ppLine27: TppLine;
    ppColumnFooterBand6: TppColumnFooterBand;
    ppFooterBand8: TppFooterBand;
    ppLine29: TppLine;
    ppLine30: TppLine;
    ppSystemVariable14: TppSystemVariable;
    ppSystemVariable15: TppSystemVariable;
    ppLabel561: TppLabel;
    ppDBText310: TppDBText;
    ppLabel588: TppLabel;
    ppDBText320: TppDBText;
    ppLine31: TppLine;
    ppLabel589: TppLabel;
    ppLine101: TppLine;
    ppLabel590: TppLabel;
    ppDBText322: TppDBText;
    ppLine103: TppLine;
    Nota_Pie_Salida: TppMemo;
    ppLabel594: TppLabel;
    ppSummaryBand21: TppSummaryBand;
    ppLine104: TppLine;
    ppLabel595: TppLabel;
    ppDBMemo5: TppDBMemo;
    ppLabel596: TppLabel;
    ppLabel597: TppLabel;
    ppDBText326: TppDBText;
    PipeSeriales_Salida: TppDBPipeline;
    Reporte_Salidas_Cliente: TppReport;
    ppParameterList4: TppParameterList;
    ppTitleBand32: TppTitleBand;
    ppLabel139: TppLabel;
    ppLabel151: TppLabel;
    ppLabel153: TppLabel;
    ppHeaderBand21: TppHeaderBand;
    Clasificacion_Sal_Cliente: TppLabel;
    ppLabel157: TppLabel;
    ppDetailBand35: TppDetailBand;
    ppDBText54: TppDBText;
    ppDBText56: TppDBText;
    ppDBText57: TppDBText;
    ppDBText61: TppDBText;
    ppDBText297: TppDBText;
    ppDBText317: TppDBText;
    ppFooterBand22: TppFooterBand;
    ppDBCalc67: TppDBCalc;
    ppLine109: TppLine;
    ppSystemVariable42: TppSystemVariable;
    ppSystemVariable43: TppSystemVariable;
    ppDBCalc77: TppDBCalc;
    ppDBCalc78: TppDBCalc;
    ppLabel562: TppLabel;
    ppLabel563: TppLabel;
    ppLabel572: TppLabel;
    ppShape23: TppShape;
    ppLabel601: TppLabel;
    ppLabel602: TppLabel;
    ppLabel603: TppLabel;
    ppLabel604: TppLabel;
    ppLabel606: TppLabel;
    ppLabel610: TppLabel;
    InventarioDespachado: TppReport;
    ppTitleBand33: TppTitleBand;
    ppLabel154: TppLabel;
    ppLabel158: TppLabel;
    ppLabel552: TppLabel;
    ppLabel557: TppLabel;
    ppHeaderBand22: TppHeaderBand;
    ppLine110: TppLine;
    ppLine111: TppLine;
    ppLabel591: TppLabel;
    ppLabel592: TppLabel;
    ppLabel593: TppLabel;
    ppLabel598: TppLabel;
    ppLabel599: TppLabel;
    ppLabel600: TppLabel;
    ppLabel605: TppLabel;
    ppLabel607: TppLabel;
    DelAl_Salida: TppLabel;
    ppSystemVariable44: TppSystemVariable;
    ppLabel609: TppLabel;
    ppLabel613: TppLabel;
    Depto_Despachada: TppLabel;
    Producto_Despachada: TppLabel;
    ppLabel616: TppLabel;
    ppLabel617: TppLabel;
    ppLabel618: TppLabel;
    ppLabel619: TppLabel;
    Usuario_Despachada: TppLabel;
    ppDetailBand36: TppDetailBand;
    ppDBText306: TppDBText;
    ppDBText318: TppDBText;
    ppDBText319: TppDBText;
    ppDBText321: TppDBText;
    ppDBText323: TppDBText;
    ppDBText324: TppDBText;
    ppDBText325: TppDBText;
    ppDBText327: TppDBText;
    ppFooterBand23: TppFooterBand;
    ppLine112: TppLine;
    ppSystemVariable45: TppSystemVariable;
    ppDBCalc75: TppDBCalc;
    ppLabel621: TppLabel;
    ppLabel622: TppLabel;
    ppLabel623: TppLabel;
    ppLabel624: TppLabel;
    ppDBCalc76: TppDBCalc;
    ppDBCalc79: TppDBCalc;
    Pipe_Mercancia_Despachada: TppDBPipeline;
    Mercancia_Cliente: TppReport;
    ppTitleBand34: TppTitleBand;
    ppShape24: TppShape;
    ppDBText328: TppDBText;
    ppDBText329: TppDBText;
    ppLabel608: TppLabel;
    ppDBText330: TppDBText;
    ppDBText331: TppDBText;
    ppHeaderBand23: TppHeaderBand;
    ppShape25: TppShape;
    ppLabel637: TppLabel;
    ppLabel638: TppLabel;
    ppLabel639: TppLabel;
    ppLabel640: TppLabel;
    ppLabel641: TppLabel;
    ppLabel642: TppLabel;
    ppLabel643: TppLabel;
    ppDetailBand37: TppDetailBand;
    ppDBText341: TppDBText;
    ppDBText342: TppDBText;
    ppDBText343: TppDBText;
    ppDBText344: TppDBText;
    ppDBText345: TppDBText;
    ppDBText346: TppDBText;
    ppSubReport6: TppSubReport;
    ppChildReport11: TppChildReport;
    ppTitleBand35: TppTitleBand;
    ppLine113: TppLine;
    ppLabel644: TppLabel;
    ppColumnHeaderBand7: TppColumnHeaderBand;
    ppDetailBand38: TppDetailBand;
    ppDBText347: TppDBText;
    ppLine114: TppLine;
    ppColumnFooterBand7: TppColumnFooterBand;
    ppFooterBand24: TppFooterBand;
    ppLine115: TppLine;
    ppLine116: TppLine;
    ppSystemVariable46: TppSystemVariable;
    ppSystemVariable47: TppSystemVariable;
    ppLine117: TppLine;
    ppLabel650: TppLabel;
    ppLine118: TppLine;
    ppLabel651: TppLabel;
    ppLabel652: TppLabel;
    ppLabel655: TppLabel;
    Pipe_Mercancia_Cliente: TppDBPipeline;
    Pipe_Seriales_Vendida_Cliente: TppDBPipeline;
    Pipe_Mercancia_Desp_Cliente: TppDBPipeline;
    Pipe_Seriales_Desp_Cliente: TppDBPipeline;
    ppGroup11: TppGroup;
    ppGroupHeaderBand10: TppGroupHeaderBand;
    ppGroupFooterBand10: TppGroupFooterBand;
    ppDBText340: TppDBText;
    ppLabel614: TppLabel;
    ppDBText332: TppDBText;
    ppDBText333: TppDBText;
    ppLabel615: TppLabel;
    ppLabel649: TppLabel;
    ppLine119: TppLine;
    ppLabel625: TppLabel;
    ppLabel626: TppLabel;
    ppLabel627: TppLabel;
    ppLabel628: TppLabel;
    ppLabel629: TppLabel;
    ppLabel630: TppLabel;
    DelAlMCliente: TppLabel;
    ppDBCalc80: TppDBCalc;
    ppDBCalc81: TppDBCalc;
    ppDBCalc82: TppDBCalc;
    ppDBCalc83: TppDBCalc;
    ppDBText334: TppDBText;
    Mercancia_Despachada_Cliente: TppReport;
    ppTitleBand36: TppTitleBand;
    ppLabel611: TppLabel;
    ppLabel612: TppLabel;
    ppLabel620: TppLabel;
    ppLabel631: TppLabel;
    ppHeaderBand24: TppHeaderBand;
    DelAlMDespCliente: TppLabel;
    ppShape26: TppShape;
    ppDBText335: TppDBText;
    ppDBText336: TppDBText;
    ppLabel633: TppLabel;
    ppDBText337: TppDBText;
    ppDBText338: TppDBText;
    ppDetailBand39: TppDetailBand;
    ppDBText339: TppDBText;
    ppDBText350: TppDBText;
    ppDBText351: TppDBText;
    ppSubReport7: TppSubReport;
    ppChildReport12: TppChildReport;
    ppTitleBand37: TppTitleBand;
    ppLine120: TppLine;
    ppLabel634: TppLabel;
    ppColumnHeaderBand8: TppColumnHeaderBand;
    ppDetailBand40: TppDetailBand;
    ppDBText352: TppDBText;
    ppLine121: TppLine;
    ppColumnFooterBand8: TppColumnFooterBand;
    ppDBText353: TppDBText;
    ppDBText354: TppDBText;
    ppFooterBand25: TppFooterBand;
    ppLine122: TppLine;
    ppLine123: TppLine;
    ppSystemVariable48: TppSystemVariable;
    ppSystemVariable49: TppSystemVariable;
    ppLine124: TppLine;
    ppLabel635: TppLabel;
    ppLine125: TppLine;
    ppLabel636: TppLabel;
    ppLabel645: TppLabel;
    ppLabel646: TppLabel;
    ppLabel647: TppLabel;
    ppDBCalc84: TppDBCalc;
    ppDBCalc85: TppDBCalc;
    ppGroup12: TppGroup;
    ppGroupHeaderBand11: TppGroupHeaderBand;
    ppDBText355: TppDBText;
    ppLabel648: TppLabel;
    ppLabel653: TppLabel;
    ppDBText356: TppDBText;
    ppShape27: TppShape;
    ppLabel654: TppLabel;
    ppLabel658: TppLabel;
    ppLabel659: TppLabel;
    ppLabel660: TppLabel;
    ppLabel661: TppLabel;
    ppGroupFooterBand11: TppGroupFooterBand;
    ppLine126: TppLine;
    ppLabel662: TppLabel;
    ppLabel663: TppLabel;
    ppDBCalc86: TppDBCalc;
    ppDBCalc87: TppDBCalc;
    ppDBText357: TppDBText;
    Pipe_Ajuste_Inventario: TppDBPipeline;
    Form_Ajuste_Inventario: TppReport;
    ppTitleBand38: TppTitleBand;
    ppLabel632: TppLabel;
    ppLabel656: TppLabel;
    ppLabel657: TppLabel;
    ppHeaderBand25: TppHeaderBand;
    ppLabel664: TppLabel;
    ppDetailBand41: TppDetailBand;
    ppDBText348: TppDBText;
    ppDBText349: TppDBText;
    ppDBText359: TppDBText;
    ppDBText360: TppDBText;
    ppFooterBand26: TppFooterBand;
    ppLine127: TppLine;
    ppSystemVariable50: TppSystemVariable;
    ppSystemVariable51: TppSystemVariable;
    ppGroup13: TppGroup;
    ppGroupHeaderBand12: TppGroupHeaderBand;
    ppLine129: TppLine;
    ppLabel684: TppLabel;
    ppLabel685: TppLabel;
    ppLabel687: TppLabel;
    ppLabel688: TppLabel;
    ppLine130: TppLine;
    ppLabel690: TppLabel;
    ppGroupFooterBand12: TppGroupFooterBand;
    ppDBCalc89: TppDBCalc;
    ppLabel693: TppLabel;
    ppLine131: TppLine;
    ppShape28: TppShape;
    ppDBText358: TppDBText;
    ppDBText361: TppDBText;
    Form_Plantilla_Conteo: TppReport;
    ppTitleBand39: TppTitleBand;
    ppLabel665: TppLabel;
    ppLabel666: TppLabel;
    ppLabel667: TppLabel;
    ppHeaderBand26: TppHeaderBand;
    ppLabel668: TppLabel;
    ppDetailBand42: TppDetailBand;
    ppDBText362: TppDBText;
    ppDBText363: TppDBText;
    Dt_Existencia_Actual: TppDBText;
    ppFooterBand27: TppFooterBand;
    ppLine128: TppLine;
    ppSystemVariable52: TppSystemVariable;
    ppSystemVariable53: TppSystemVariable;
    ppGroup14: TppGroup;
    ppGroupHeaderBand13: TppGroupHeaderBand;
    ppLine132: TppLine;
    ppLabel669: TppLabel;
    ppLabel670: TppLabel;
    Lbl_Existencia_Actual: TppLabel;
    ppLabel672: TppLabel;
    ppLine133: TppLine;
    ppShape29: TppShape;
    ppDBText367: TppDBText;
    ppGroupFooterBand13: TppGroupFooterBand;
    ppDBCalc88: TppDBCalc;
    ppLabel674: TppLabel;
    ppLine134: TppLine;
    ppLine135: TppLine;
    PipeCotizaciones: TppDBPipeline;
    PipeDetalleCotizaciones: TppDBPipeline;
    FormCotizacion: TppReport;
    ppTitleBand40: TppTitleBand;
    ppShape30: TppShape;
    ppDBText364: TppDBText;
    ppDBText365: TppDBText;
    ppLabel671: TppLabel;
    ppDBText366: TppDBText;
    ppDBText368: TppDBText;
    ppLabel673: TppLabel;
    ppDBText369: TppDBText;
    ppLabel675: TppLabel;
    ppDBText370: TppDBText;
    ppLabel676: TppLabel;
    ppDBText371: TppDBText;
    ppLabel677: TppLabel;
    ppDBText372: TppDBText;
    ppLabel678: TppLabel;
    ppLabel679: TppLabel;
    ppLabel680: TppLabel;
    ppLabel681: TppLabel;
    ppLabel682: TppLabel;
    ppDBText374: TppDBText;
    ppLabel689: TppLabel;
    ppLabel691: TppLabel;
    ppHeaderBand27: TppHeaderBand;
    ppShape31: TppShape;
    ppLabel695: TppLabel;
    ppLabel696: TppLabel;
    ppLabel697: TppLabel;
    ppLabel698: TppLabel;
    ppLabel699: TppLabel;
    ppLabel700: TppLabel;
    ppLabel701: TppLabel;
    ppDetailBand43: TppDetailBand;
    ppDBText377: TppDBText;
    ppDBText378: TppDBText;
    ppDBText379: TppDBText;
    ppDBText380: TppDBText;
    ppDBText381: TppDBText;
    ppDBText382: TppDBText;
    ppDBText383: TppDBText;
    ppFooterBand28: TppFooterBand;
    ppLine138: TppLine;
    ppLine139: TppLine;
    ppSystemVariable54: TppSystemVariable;
    ppSystemVariable55: TppSystemVariable;
    ppLabel703: TppLabel;
    ppDBText385: TppDBText;
    CotInvoiceTaxLabel: TppLabel;
    CotInvoiceTax: TppDBText;
    CotInvoiceDiscountLabel: TppLabel;
    CotInvoiceDiscount: TppDBText;
    ppLabel707: TppLabel;
    ppDBText389: TppDBText;
    ppLine140: TppLine;
    ppLabel708: TppLabel;
    ppLine141: TppLine;
    ppLabel709: TppLabel;
    ppDBText391: TppDBText;
    ppLine142: TppLine;
    Nota_Pie_Cotizacion: TppMemo;
    ppLabel713: TppLabel;
    ppSummaryBand23: TppSummaryBand;
    ppLine143: TppLine;
    ppLabel714: TppLabel;
    ppDBMemo6: TppDBMemo;
    ppLabel715: TppLabel;
    ppLabel716: TppLabel;
    ppDBText395: TppDBText;
    ppParameterList5: TppParameterList;
    ppImage9: TppImage;
    ppLabel537: TppLabel;
    ppLabel683: TppLabel;
    ppLabel686: TppLabel;
    CatalogoProductos_Categoria: TppReport;
    ppTitleBand41: TppTitleBand;
    ppLabel692: TppLabel;
    ppLabel694: TppLabel;
    ppLabel702: TppLabel;
    ppHeaderBand28: TppHeaderBand;
    ppLabel704: TppLabel;
    ppDetailBand44: TppDetailBand;
    ppDBText293: TppDBText;
    ppDBText373: TppDBText;
    Precio_Catalogo: TppVariable;
    ppFooterBand29: TppFooterBand;
    ppLine99: TppLine;
    ppSystemVariable56: TppSystemVariable;
    ppSystemVariable57: TppSystemVariable;
    ppGroup15: TppGroup;
    ppGroupHeaderBand14: TppGroupHeaderBand;
    Cat_NombreCategoria: TppLabel;
    Cat_Num_Categoria: TppLabel;
    ppGroupFooterBand14: TppGroupFooterBand;
    ppDBCalc91: TppDBCalc;
    ppLabel740: TppLabel;
    ppLine145: TppLine;
    Cat_Nombre_Categoria: TppLabel;
    ppParameterList6: TppParameterList;
    ppColumnHeaderBand9: TppColumnHeaderBand;
    ppColumnFooterBand9: TppColumnFooterBand;
    Foto_Catalogo: TppImage;
    ppShape32: TppShape;
    FormRegistro_Gastos: TppReport;
    ppTitleBand42: TppTitleBand;
    ppLabel705: TppLabel;
    ppDBText384: TppDBText;
    ppLabel706: TppLabel;
    ppDBText387: TppDBText;
    ppLabel710: TppLabel;
    ppDBText388: TppDBText;
    ppLabel717: TppLabel;
    ppImage11: TppImage;
    ppLabel718: TppLabel;
    ppLabel719: TppLabel;
    ppLabel720: TppLabel;
    ppLabel721: TppLabel;
    ppLabel722: TppLabel;
    ppLabel725: TppLabel;
    ppDBText393: TppDBText;
    ppLabel726: TppLabel;
    ppDetailBand45: TppDetailBand;
    ppFooterBand30: TppFooterBand;
    ppLine144: TppLine;
    ppSystemVariable58: TppSystemVariable;
    ppSystemVariable59: TppSystemVariable;
    ppLabel739: TppLabel;
    ppDBText405: TppDBText;
    ppLabel742: TppLabel;
    ppDBText407: TppDBText;
    ppLabel744: TppLabel;
    ppDBText409: TppDBText;
    ppLine146: TppLine;
    ppLabel745: TppLabel;
    ppLine147: TppLine;
    ppLabel746: TppLabel;
    ppDBText411: TppDBText;
    ppLine148: TppLine;
    Nota_Pie_Reg_Gastos: TppMemo;
    ppSummaryBand24: TppSummaryBand;
    ppDBMemo7: TppDBMemo;
    ppLabel751: TppLabel;
    ppDBText414: TppDBText;
    ppParameterList7: TppParameterList;
    pipeRegistro_Gastos: TppDBPipeline;
    ppLabel711: TppLabel;
    ppLabel712: TppLabel;
    ppDBText390: TppDBText;
    ppLabel723: TppLabel;
    ppDBText392: TppDBText;
    ppLabel724: TppLabel;
    ppDBMemo8: TppDBMemo;
    Reporte_Gastos: TppReport;
    ppTitleBand43: TppTitleBand;
    ppLabel727: TppLabel;
    ppLabel728: TppLabel;
    ppLabel729: TppLabel;
    ppHeaderBand29: TppHeaderBand;
    Clasificacion_Gastos: TppLabel;
    ppLabel731: TppLabel;
    ppDetailBand46: TppDetailBand;
    ppDBText375: TppDBText;
    ppDBText376: TppDBText;
    ppDBText386: TppDBText;
    ppDBText394: TppDBText;
    ppDBText396: TppDBText;
    ppDBText399: TppDBText;
    ppDBText400: TppDBText;
    ppFooterBand31: TppFooterBand;
    ppDBCalc90: TppDBCalc;
    ppLine136: TppLine;
    ppSystemVariable60: TppSystemVariable;
    ppSystemVariable61: TppSystemVariable;
    ppDBCalc94: TppDBCalc;
    ppDBCalc95: TppDBCalc;
    ppLine149: TppLine;
    ppLabel737: TppLabel;
    ppLabel738: TppLabel;
    ppLabel741: TppLabel;
    ppShape34: TppShape;
    ppLabel760: TppLabel;
    ppLabel761: TppLabel;
    ppLabel762: TppLabel;
    ppLabel763: TppLabel;
    ppLabel766: TppLabel;
    ppLabel767: TppLabel;
    pipe_Listado_Gastos: TppDBPipeline;
    ppDBText397: TppDBText;
    ppDBMemo9: TppDBMemo;
    ppLabel764: TppLabel;
    ppLabel765: TppLabel;
    ppLabel769: TppLabel;
    ppLine137: TppLine;
    Reporte_Listado_Trabajos: TppReport;
    ppTitleBand45: TppTitleBand;
    ppLabel753: TppLabel;
    ppLabel754: TppLabel;
    ppLabel755: TppLabel;
    ppHeaderBand31: TppHeaderBand;
    Clasificacion_Listado_Trabajo: TppLabel;
    ppLabel757: TppLabel;
    ppDetailBand48: TppDetailBand;
    ppDBText402: TppDBText;
    ppDBText403: TppDBText;
    ppFooterBand33: TppFooterBand;
    ppLine151: TppLine;
    ppSystemVariable64: TppSystemVariable;
    ppSystemVariable65: TppSystemVariable;
    ppSummaryBand26: TppSummaryBand;
    ppShape37: TppShape;
    ppLabel795: TppLabel;
    ppLabel796: TppLabel;
    ppLabel801: TppLabel;
    ppDBText419: TppDBText;
    ppDBText408: TppDBText;
    ppLabel778: TppLabel;
    ppDBText410: TppDBText;
    ppLabel779: TppLabel;
    ppGroup16: TppGroup;
    ppGroupHeaderBand15: TppGroupHeaderBand;
    ppGroupFooterBand15: TppGroupFooterBand;
    frmComprobante_Entrega: TppReport;
    ppTitleBand46: TppTitleBand;
    ppShape36: TppShape;
    ppDBText412: TppDBText;
    ppLabel756: TppLabel;
    ppLabel758: TppLabel;
    ppDBText413: TppDBText;
    ppLabel759: TppLabel;
    ppDBText415: TppDBText;
    ppLabel772: TppLabel;
    ppImage13: TppImage;
    ppLabel773: TppLabel;
    ppLabel774: TppLabel;
    ppLabel775: TppLabel;
    ppLabel776: TppLabel;
    ppLabel777: TppLabel;
    ppLabel780: TppLabel;
    ppDBText420: TppDBText;
    ppLabel781: TppLabel;
    ppHeaderBand32: TppHeaderBand;
    ppShape38: TppShape;
    ppLabel784: TppLabel;
    ppLabel785: TppLabel;
    ppLabel786: TppLabel;
    ppDetailBand49: TppDetailBand;
    ppDBText421: TppDBText;
    ppDBText422: TppDBText;
    ppDBText423: TppDBText;
    ppFooterBand34: TppFooterBand;
    ppLine155: TppLine;
    ppSystemVariable66: TppSystemVariable;
    ppSystemVariable67: TppSystemVariable;
    ppLine157: TppLine;
    ppLabel788: TppLabel;
    ppLabel790: TppLabel;
    ppDBText424: TppDBText;
    ppLine159: TppLine;
    ppSummaryBand27: TppSummaryBand;
    ppLine160: TppLine;
    ppLabel792: TppLabel;
    ppParameterList9: TppParameterList;
    Pipe_Formas_Pago: TppDBPipeline;
    PipeAcuerdos: TppDBPipeline;
    PipeDetalles_Acuerdos: TppDBPipeline;
    FormAcuerdos: TppReport;
    ppTitleBand47: TppTitleBand;
    ppLabel797: TppLabel;
    ppDBText431: TppDBText;
    ppLabel802: TppLabel;
    ppImage14: TppImage;
    ppLabel803: TppLabel;
    ppLabel804: TppLabel;
    ppLabel805: TppLabel;
    ppLabel806: TppLabel;
    ppLabel814: TppLabel;
    ppDBText438: TppDBText;
    ppLabel815: TppLabel;
    ppDBText439: TppDBText;
    ppLabel816: TppLabel;
    ppLabel817: TppLabel;
    ppHeaderBand33: TppHeaderBand;
    ppShape40: TppShape;
    ppLabel818: TppLabel;
    ppLabel819: TppLabel;
    ppLabel820: TppLabel;
    ppLabel824: TppLabel;
    ppDetailBand50: TppDetailBand;
    ppDBText440: TppDBText;
    ppDBText441: TppDBText;
    ppDBText442: TppDBText;
    ppDBText446: TppDBText;
    ppFooterBand35: TppFooterBand;
    ppSystemVariable68: TppSystemVariable;
    ppSystemVariable69: TppSystemVariable;
    ppLabel830: TppLabel;
    ppDBText452: TppDBText;
    ppLine163: TppLine;
    ppLabel831: TppLabel;
    ppLine164: TppLine;
    ppLabel832: TppLabel;
    ppDBText454: TppDBText;
    ppSummaryBand28: TppSummaryBand;
    ppLine166: TppLine;
    ppLabel836: TppLabel;
    ppParameterList10: TppParameterList;
    ppDBText426: TppDBText;
    ppLabel798: TppLabel;
    ppLabel799: TppLabel;
    ppLine162: TppLine;
    Reporte_Listado_Acuerdos: TppReport;
    ppParameterList11: TppParameterList;
    ppTitleBand48: TppTitleBand;
    ppLabel807: TppLabel;
    ppLabel808: TppLabel;
    ppLabel821: TppLabel;
    ppHeaderBand34: TppHeaderBand;
    Clasificacion_Listado_Acuerdos: TppLabel;
    ppLabel823: TppLabel;
    ppDetailBand51: TppDetailBand;
    ppDBText427: TppDBText;
    ppDBText428: TppDBText;
    ppDBText432: TppDBText;
    ppDBText433: TppDBText;
    ppDBText429: TppDBText;
    ppFooterBand36: TppFooterBand;
    ppLine158: TppLine;
    ppSystemVariable70: TppSystemVariable;
    ppSystemVariable71: TppSystemVariable;
    ppSummaryBand29: TppSummaryBand;
    ppShape41: TppShape;
    ppLabel825: TppLabel;
    ppLabel826: TppLabel;
    ppLabel828: TppLabel;
    ppLabel829: TppLabel;
    ppLabel827: TppLabel;
    ppGroup18: TppGroup;
    ppGroupHeaderBand17: TppGroupHeaderBand;
    ppGroupFooterBand17: TppGroupFooterBand;
    Reporte_Facturas_Moneda: TppReport;
    ppTitleBand49: TppTitleBand;
    ppLabel822: TppLabel;
    ppLabel833: TppLabel;
    ppLabel834: TppLabel;
    ppHeaderBand35: TppHeaderBand;
    Clasificacion_Fact_Moneda: TppLabel;
    ppLabel837: TppLabel;
    ppDetailBand52: TppDetailBand;
    ppDBText443: TppDBText;
    ppDBText444: TppDBText;
    ppDBText445: TppDBText;
    ppDBText447: TppDBText;
    ppDBText448: TppDBText;
    ppDBText451: TppDBText;
    ppDBText453: TppDBText;
    ppDBText455: TppDBText;
    ppFooterBand37: TppFooterBand;
    ppDBCalc92: TppDBCalc;
    ppLine161: TppLine;
    ppSystemVariable72: TppSystemVariable;
    ppSystemVariable73: TppSystemVariable;
    ppDBCalc93: TppDBCalc;
    ppDBCalc96: TppDBCalc;
    ppDBCalc97: TppDBCalc;
    ppDBCalc98: TppDBCalc;
    ppLabel838: TppLabel;
    ppLabel839: TppLabel;
    ppLine167: TppLine;
    ppDBCalc99: TppDBCalc;
    ppLabel842: TppLabel;
    ppLabel843: TppLabel;
    ppLabel844: TppLabel;
    ppLabel845: TppLabel;
    ppGroup17: TppGroup;
    ppGroupHeaderBand16: TppGroupHeaderBand;
    ppShape43: TppShape;
    ppLabel859: TppLabel;
    ppLabel860: TppLabel;
    ppLabel861: TppLabel;
    ppLabel862: TppLabel;
    ppLabel863: TppLabel;
    ppLabel864: TppLabel;
    ppLabel865: TppLabel;
    ppLabel866: TppLabel;
    ppLabel867: TppLabel;
    ppGroupFooterBand16: TppGroupFooterBand;
    ppLine172: TppLine;
    ppLine173: TppLine;
    ppDBCalc102: TppDBCalc;
    ppDBCalc103: TppDBCalc;
    ppDBCalc104: TppDBCalc;
    ppDBCalc105: TppDBCalc;
    ppLabel870: TppLabel;
    ppLabel871: TppLabel;
    ppLabel872: TppLabel;
    ppDBCalc106: TppDBCalc;
    ppDBCalc107: TppDBCalc;
    ppLabel873: TppLabel;
    ppLabel874: TppLabel;
    ppLabel875: TppLabel;
    ppLabel876: TppLabel;
    ppLabel846: TppLabel;
    ppDBText449: TppDBText;
    Nombre_Moneda: TppLabel;
    ppLabel794: TppLabel;
    ppDBText435: TppDBText;
    ppDBText436: TppDBText;
    ppLabel800: TppLabel;
    ppDBMemo10: TppDBMemo;
    ppLabel809: TppLabel;
    ppLabel810: TppLabel;
    frmOrdenTrabajo: TppReport;
    ppTitleBand50: TppTitleBand;
    ppLabel811: TppLabel;
    ppDBText437: TppDBText;
    ppLabel812: TppLabel;
    ppImage15: TppImage;
    ppLabel813: TppLabel;
    ppLabel835: TppLabel;
    ppLabel840: TppLabel;
    ppLabel841: TppLabel;
    ppLabel847: TppLabel;
    ppDBText450: TppDBText;
    ppLabel848: TppLabel;
    ppDBText456: TppDBText;
    ppLabel849: TppLabel;
    ppLabel850: TppLabel;
    ppDBText457: TppDBText;
    ppLabel851: TppLabel;
    ppLabel852: TppLabel;
    ppDBMemo11: TppDBMemo;
    ppLabel853: TppLabel;
    ppLabel854: TppLabel;
    ppHeaderBand36: TppHeaderBand;
    ppShape39: TppShape;
    ppLabel855: TppLabel;
    ppLabel856: TppLabel;
    ppLabel857: TppLabel;
    ppLabel868: TppLabel;
    ppLabel869: TppLabel;
    ppDetailBand53: TppDetailBand;
    ppDBText458: TppDBText;
    ppDBText459: TppDBText;
    ppDBText460: TppDBText;
    ppDBText462: TppDBText;
    ppDBText463: TppDBText;
    ppSystemVariable74: TppSystemVariable;
    ppSystemVariable75: TppSystemVariable;
    ppLine168: TppLine;
    ppLabel878: TppLabel;
    ppLine169: TppLine;
    ppLabel879: TppLabel;
    ppDBText465: TppDBText;
    ppSummaryBand30: TppSummaryBand;
    ppLine170: TppLine;
    ppLabel880: TppLabel;
    ppParameterList12: TppParameterList;
    ppDBText398: TppDBText;
    ppLabel730: TppLabel;
    ppDBText401: TppDBText;
    ppLabel732: TppLabel;
    ppLabel733: TppLabel;
    RecargasVendidas: TppReport;
    ppTitleBand44: TppTitleBand;
    Titulo_Recargas: TppLabel;
    ppLabel735: TppLabel;
    ppLabel736: TppLabel;
    ppLabel743: TppLabel;
    ppHeaderBand30: TppHeaderBand;
    ppLine150: TppLine;
    ppLine152: TppLine;
    ppLabel747: TppLabel;
    ppLabel748: TppLabel;
    ppLabel749: TppLabel;
    ppLabel750: TppLabel;
    ppLabel752: TppLabel;
    lblBeneficio: TppLabel;
    ppLabel771: TppLabel;
    DelAl_Recargas: TppLabel;
    ppSystemVariable62: TppSystemVariable;
    ppDetailBand47: TppDetailBand;
    ppDBText404: TppDBText;
    ppDBText406: TppDBText;
    ppDBText416: TppDBText;
    ppDBText417: TppDBText;
    ppDBText430: TppDBText;
    fldBeneficio: TppDBText;
    ppDBText461: TppDBText;
    ppFooterBand32: TppFooterBand;
    ppLine153: TppLine;
    ppSystemVariable63: TppSystemVariable;
    ppDBCalc100: TppDBCalc;
    ltBeneficio: TppLabel;
    ppLabel886: TppLabel;
    ppLabel887: TppLabel;
    ppLabel888: TppLabel;
    tBeneficio: TppDBCalc;
    ppDBCalc108: TppDBCalc;
    ppGroup19: TppGroup;
    ppGroupHeaderBand18: TppGroupHeaderBand;
    ppGroupFooterBand18: TppGroupFooterBand;
    ppShape33: TppShape;
    ppDBText464: TppDBText;
    ppDBText466: TppDBText;
    ppLabel734: TppLabel;
    ppDBText467: TppDBText;
    ppDBText468: TppDBText;
    ppLine154: TppLine;
    ppDBCalc109: TppDBCalc;
    ppLabel768: TppLabel;
    sbBeneficio: TppDBCalc;
    ppDBCalc111: TppDBCalc;
    ppDBCalc101: TppDBCalc;
    ppLabel163: TppLabel;
    ppLabel169: TppLabel;
    ppLabel170: TppLabel;
    ppLabel770: TppLabel;
    ppLabel782: TppLabel;
    ppDBCalc31: TppDBCalc;
    ppVariable10: TppVariable;
    ppVariable12: TppVariable;
    ppLabel412: TppLabel;
    ppLabel413: TppLabel;
    ppLabel414: TppLabel;
    ppDBCalc110: TppDBCalc;
    ppLabel783: TppLabel;
    ppLabel787: TppLabel;
    ppLabel789: TppLabel;
    ppLabel858: TppLabel;
    ppLabel877: TppLabel;
    Nombre_Categoria: TppLabel;
    ppLabel881: TppLabel;
    ppDBText72: TppDBText;
    ppTitleBand23: TppTitleBand;
    ppLabel155: TppLabel;
    ppLabel156: TppLabel;
    ppLabel159: TppLabel;
    ppHeaderBand18: TppHeaderBand;
    ppLabel160: TppLabel;
    ppLabel161: TppLabel;
    ppDetailBand26: TppDetailBand;
    ppDBText59: TppDBText;
    ppDBText60: TppDBText;
    ppDBText63: TppDBText;
    ppDBText64: TppDBText;
    ppDBText65: TppDBText;
    ppDBText66: TppDBText;
    ppDBText67: TppDBText;
    ppDBText68: TppDBText;
    ppDBText70: TppDBText;
    ppDBText71: TppDBText;
    ppFooterBand19: TppFooterBand;
    ppDBCalc47: TppDBCalc;
    ppLine28: TppLine;
    ppSystemVariable16: TppSystemVariable;
    ppSystemVariable17: TppSystemVariable;
    ppDBCalc48: TppDBCalc;
    ppDBCalc49: TppDBCalc;
    ppDBCalc50: TppDBCalc;
    ppDBCalc51: TppDBCalc;
    ppLabel162: TppLabel;
    ppLabel164: TppLabel;
    ppVariable7: TppVariable;
    ppLabel165: TppLabel;
    ppLabel166: TppLabel;
    ppVariable8: TppVariable;
    ppLine35: TppLine;
    ppLine36: TppLine;
    ppDBCalc52: TppDBCalc;
    ppLabel167: TppLabel;
    ppLabel168: TppLabel;
    ppLabel171: TppLabel;
    ppLabel173: TppLabel;
    ppSummaryBand4: TppSummaryBand;
    ppSubReport1: TppSubReport;
    ppChildReport5: TppChildReport;
    ppTitleBand24: TppTitleBand;
    ppLine54: TppLine;
    ppLabel176: TppLabel;
    ppLabel177: TppLabel;
    ppLabel189: TppLabel;
    ppLabel191: TppLabel;
    ppLabel192: TppLabel;
    ppLabel193: TppLabel;
    ppDetailBand27: TppDetailBand;
    ppShape2: TppShape;
    ppDBText73: TppDBText;
    ppDBText74: TppDBText;
    ppDBText75: TppDBText;
    ppDBText77: TppDBText;
    ppDBText78: TppDBText;
    ppSummaryBand12: TppSummaryBand;
    ppDBCalc53: TppDBCalc;
    ppLabel296: TppLabel;
    ppLine81: TppLine;
    ppSubReport2: TppSubReport;
    ppChildReport6: TppChildReport;
    ppTitleBand25: TppTitleBand;
    ppLine82: TppLine;
    ppLabel303: TppLabel;
    ppLabel304: TppLabel;
    ppLabel333: TppLabel;
    ppLabel334: TppLabel;
    ppLabel341: TppLabel;
    ppDetailBand28: TppDetailBand;
    ppDBText91: TppDBText;
    ppDBText94: TppDBText;
    ppDBText168: TppDBText;
    ppDBText188: TppDBText;
    ppSummaryBand17: TppSummaryBand;
    ppLabel364: TppLabel;
    ppDBCalc54: TppDBCalc;
    ppLine83: TppLine;
    ppGroup7: TppGroup;
    ppGroupHeaderBand8: TppGroupHeaderBand;
    ppShape16: TppShape;
    ppLabel368: TppLabel;
    ppLabel392: TppLabel;
    ppLabel474: TppLabel;
    ppLabel475: TppLabel;
    ppLabel476: TppLabel;
    ppDBText211: TppDBText;
    ppLabel477: TppLabel;
    ppLabel478: TppLabel;
    ppLabel479: TppLabel;
    ppLabel480: TppLabel;
    ppLabel481: TppLabel;
    ppLabel482: TppLabel;
    ppGroupFooterBand6: TppGroupFooterBand;
    ppLine84: TppLine;
    ppLine85: TppLine;
    ppDBCalc55: TppDBCalc;
    ppDBCalc56: TppDBCalc;
    ppDBCalc57: TppDBCalc;
    ppDBCalc58: TppDBCalc;
    ppLabel483: TppLabel;
    ppLabel484: TppLabel;
    ppLabel485: TppLabel;
    ppDBText215: TppDBText;
    ppDBCalc59: TppDBCalc;
    ppDBCalc60: TppDBCalc;
    ppLabel486: TppLabel;
    ppLabel487: TppLabel;
    ppLabel488: TppLabel;
    ppLabel489: TppLabel;
    InvoiceTitleBand: TppTitleBand;
    ppShape17: TppShape;
    ppDBText223: TppDBText;
    ppDBText258: TppDBText;
    ppLabel490: TppLabel;
    ppDBText259: TppDBText;
    ppDBText260: TppDBText;
    ppLabel491: TppLabel;
    ppDBText261: TppDBText;
    ppLabel492: TppLabel;
    ppDBText262: TppDBText;
    ppDBText263: TppDBText;
    ppLabel493: TppLabel;
    ppDBText264: TppDBText;
    ppLabel494: TppLabel;
    Logo: TppImage;
    InvoiceCompanyAddress: TppLabel;
    InvoiceCompanyPhone: TppLabel;
    InvoiceCompanyName: TppLabel;
    ppLabel495: TppLabel;
    ppLabel496: TppLabel;
    ppLabel497: TppLabel;
    ppLabel498: TppLabel;
    ppDBText265: TppDBText;
    ppLabel499: TppLabel;
    ppDBText266: TppDBText;
    ppLabel500: TppLabel;
    ppLabel501: TppLabel;
    ppLabel502: TppLabel;
    ppDBText267: TppDBText;
    ppLabel503: TppLabel;
    ppDBText425: TppDBText;
    ppLabel791: TppLabel;
    ppLabel793: TppLabel;
    InvoiceHeaderBand: TppHeaderBand;
    Squared: TppShape;
    ppLabel504: TppLabel;
    ppLabel505: TppLabel;
    ppLabel506: TppLabel;
    ppLabel507: TppLabel;
    ppLabel508: TppLabel;
    ppLabel509: TppLabel;
    ppLabel510: TppLabel;
    ppDetailBand11: TppDetailBand;
    Codigo: TppDBText;
    ppDBText268: TppDBText;
    ppDBText269: TppDBText;
    ppDBText270: TppDBText;
    ppDBText271: TppDBText;
    ppDBText272: TppDBText;
    ppDBText273: TppDBText;
    ppSubReport3: TppSubReport;
    ppChildReport8: TppChildReport;
    ppTitleBand28: TppTitleBand;
    ppLine97: TppLine;
    ppLabel535: TppLabel;
    ppColumnHeaderBand5: TppColumnHeaderBand;
    ppDetailBand31: TppDetailBand;
    ppDBText291: TppDBText;
    ppLine98: TppLine;
    ppColumnFooterBand5: TppColumnFooterBand;
    InvoiceFooterBand: TppFooterBand;
    FooterLine: TppLine;
    ppSystemVariable36: TppSystemVariable;
    ppSystemVariable37: TppSystemVariable;
    ppLabel511: TppLabel;
    ppDBText274: TppDBText;
    InvoicePendingLabel: TppLabel;
    InvoicePendingAmmount: TppDBText;
    InvoiceTaxLabel: TppLabel;
    InvoiceTax: TppDBText;
    InvoiceDiscountLabel: TppLabel;
    InvoiceDiscount: TppDBText;
    LSubTotal: TppLabel;
    Sub_Total: TppDBText;
    ppLine86: TppLine;
    ppLabel512: TppLabel;
    ppLine87: TppLine;
    ppLabel513: TppLabel;
    InvoicePaidLabel: TppLabel;
    InvoicePaidAmmount: TppDBText;
    ppDBText275: TppDBText;
    ppLine88: TppLine;
    ppLabel514: TppLabel;
    ppDBText276: TppDBText;
    ppLabel515: TppLabel;
    ppDBText277: TppDBText;
    Nota_Pie_Factura: TppMemo;
    ppDBText470: TppDBText;
    ppSummaryBand18: TppSummaryBand;
    ppLine89: TppLine;
    ppLabel516: TppLabel;
    ppDBMemo2: TppDBMemo;
    ppLabel517: TppLabel;
    ppDBText278: TppDBText;
    ppLabel882: TppLabel;
    ppDBText418: TppDBText;
    ppDBText469: TppDBText;
    procedure ppDetailBand11BeforePrint(Sender: TObject);
    procedure InvoiceTitleBandBeforePrint(Sender: TObject);
    procedure ppLabel282Print(Sender: TObject);
    procedure ReporteProductos_FabricanteBeforePrint(Sender: TObject);
    procedure ppVariable5Calc(Sender: TObject; var Value: Variant);
    procedure ppVariable3Calc(Sender: TObject; var Value: Variant);
    procedure ppVariable11Calc(Sender: TObject; var Value: Variant);
    procedure ppVariable9Calc(Sender: TObject; var Value: Variant);
    procedure Print_Costo(Sender: TObject);
    procedure Set_Cost_Type(Sender: TObject);
    procedure Define_Print_Cost(Sender: TObject);
    procedure ReportHeaderName(Sender: TObject);
    procedure ReportHeaderAddress(Sender: TObject);
    procedure ReportHeaderPhones(Sender: TObject);
    procedure CabezaGrupoBeforePrint(Sender: TObject);
    procedure Total_Costo_Calc(Sender: TObject; var Value: Variant);
    procedure PrecioContadoCalc(Sender: TObject; var Value: Variant);
    procedure PrecioCreditoCalc(Sender: TObject; var Value: Variant);
    procedure PrecioMinimoCalc(Sender: TObject; var Value: Variant);
    procedure PieGrupoAfterPrint(Sender: TObject);
    procedure ppGroupHeaderBand1BeforePrint(Sender: TObject);
    procedure MESCalc(Sender: TObject; var Value: Variant);
    procedure UserPrint(Sender: TObject);
    procedure ValorLetrasPrint(Sender: TObject);
    procedure LogoPrint(Sender: TObject);
    procedure ppGroupHeaderBand6BeforePrint(Sender: TObject);
    procedure TCostoPromedio_CategoriaCalc(Sender: TObject; var Value: Variant);
    procedure TGPrecioContado_CategoriaCalc(Sender: TObject;
      var Value: Variant);
    procedure TPrecioContado_CategoriaCalc(Sender: TObject; var Value: Variant);
    procedure TGCostoPromedio_CategoriaCalc(Sender: TObject;
      var Value: Variant);
    procedure ppHeaderBand15BeforePrint(Sender: TObject);
    procedure ppHeaderBand11BeforePrint(Sender: TObject);
    procedure ppDetailBand15BeforePrint(Sender: TObject);
    procedure ppGroupHeaderBand14BeforePrint(Sender: TObject);
    procedure ppDetailBand44BeforePrint(Sender: TObject);
    procedure ppGroupHeaderBand16BeforePrint(Sender: TObject);
    procedure ppGroupHeaderBand18BeforePrint(Sender: TObject);
    procedure ppDetailBand47BeforePrint(Sender: TObject);
    procedure TGCostoPromedio_CategoriaPrint(Sender: TObject);
    procedure TGPrecioContado_CategoriaPrint(Sender: TObject);
  private
    { Private declarations }
  public
    { Public declarations }
    _Seccion : String;
  end;

var
  ReportsAndForms      : TReportsAndForms;

implementation

uses DataModulo, Utilidades, DB;

{$R *.dfm}

procedure TReportsAndForms.ReportHeaderName(Sender: TObject);
begin
  RegInfo.CloseKey;
  RegInfo.OpenKey(_GeneralConfigKey,False);
  {Informacion  General}
  RegInfo.CloseKey;
  RegInfo.OpenKey(_CompanyInfoKey,False);
  (Sender as TppLabel).Caption         := Unencrypt(RegInfo.ReadString(_UserCompName));
  (Sender as TppLabel).Alignment := TAlignment(RegInfo.ReadInteger(_UserCompAlignment));

  {Alineación}
  If Trim(_Seccion) <> '' Then
    Begin
      RegInfo.CloseKey;
      RegInfo.OpenKey(_Seccion,False);
      (Sender as TppLabel).Alignment := TAlignment(RegInfo.ReadInteger(_Alignment))
    End
end;

procedure TReportsAndForms.ReporteProductos_FabricanteBeforePrint(
  Sender: TObject);
begin
  TCostoPromedio.AsCurrency := 0;
  TGCostoPromedio.AsCurrency := 0;
  TPrecioContado.AsCurrency := 0;
  TGPrecioContado.AsCurrency := 0;
end;

procedure TReportsAndForms.ReportHeaderAddress(Sender: TObject);
begin
  RegInfo.CloseKey;
  RegInfo.OpenKey(_GeneralConfigKey,False);
  {Informacion  General}
  RegInfo.CloseKey;
  RegInfo.OpenKey(_CompanyInfoKey,False);
  (Sender As TppLabel).Caption := Format ('%s, %s, %s',[Unencrypt(RegInfo.ReadString(_UserCompAddres)),
                                                         Unencrypt(RegInfo.ReadString(_UserCompCity)),
                                                         Unencrypt(RegInfo.ReadString(_UserCompCountry))]);

  {Alineación}
  (Sender as TppLabel).Alignment := TAlignment(RegInfo.ReadInteger(_UserCompAlignment));

  If Trim(_Seccion) <> '' Then
    Begin
      RegInfo.CloseKey;
      RegInfo.OpenKey(_Seccion,False);
      (Sender as TppLabel).Alignment := TAlignment(RegInfo.ReadInteger(_Alignment))
    End
end;

procedure TReportsAndForms.ReportHeaderPhones(Sender: TObject);
begin
  RegInfo.CloseKey;
  RegInfo.OpenKey(_GeneralConfigKey,False);
  {Informacion  General}
  RegInfo.CloseKey;
  RegInfo.OpenKey(_CompanyInfoKey,False);
  (Sender As TppLabel).Caption      := Format ('%s, %s, %s',[Unencrypt(RegInfo.ReadString(_UserCompPhone1)),
                                                         Unencrypt(RegInfo.ReadString(_UserCompPhone2)),
                                                         Unencrypt(RegInfo.ReadString(_UserCompRNC))]);
  {Alineación}
  (Sender as TppLabel).Alignment := TAlignment(RegInfo.ReadInteger(_UserCompAlignment));

  If Trim(_Seccion) <> '' Then
    Begin
      RegInfo.CloseKey;
      RegInfo.OpenKey(_Seccion,False);
      (Sender as TppLabel).Alignment := TAlignment(RegInfo.ReadInteger(_Alignment))
    End
end;

procedure TReportsAndForms.Set_Cost_Type(Sender: TObject);
begin
  If Trim(PipeReportes.DataSource.DataSet.FieldByName('Metodo_Calculo_Costo').AsString) = 'Promedio' Then
    (Sender As TppLabel).Caption := 'P';

  If Trim(PipeReportes.DataSource.DataSet.FieldByName('Metodo_Calculo_Costo').AsString) = 'Estandar' Then
    (Sender As TppLabel).Caption := 'E';

  If Trim(PipeReportes.DataSource.DataSet.FieldByName('Metodo_Calculo_Costo').AsString) = 'Última Compra' Then
    (Sender As TppLabel).Caption := 'U';

  Print_Costo(Sender)
end;

procedure TReportsAndForms.CabezaGrupoBeforePrint(Sender: TObject);
begin
  NombreFabricante_Proveedor.Caption := 'No Definido';
  Num_Fabricante.Caption := Pad('L',Modulo.tReporter.FieldByName('Fabricante').AsString,6,'0');
  Num_Fabricante_Proveedor.Caption := Pad('L',Modulo.tReporter.FieldByName('Fabricante').AsString,6,'0');
  If Modulo.tFabricante.Locate(Modulo.tFabricanteNumero.FieldName,
                                    Modulo.tReporter.FieldByName('Fabricante').AsInteger,
                                    []) Then NombreFabricante_Proveedor.Caption := Modulo.tFabricanteNombre.Value;

  NombreFabricante.Caption := NombreFabricante_Proveedor.Caption;
  Nombre_Fabricante_Proveedor.Caption := NombreFabricante_Proveedor.Caption;
  Nombre_Fabricante.Caption := NombreFabricante_Proveedor.Caption
end;

procedure TReportsAndForms.TCostoPromedio_CategoriaCalc(Sender: TObject;
  var Value: Variant);
begin
  Value := TCostoPromedio.AsCurrency
end;

procedure TReportsAndForms.TGCostoPromedio_CategoriaCalc(Sender: TObject;
  var Value: Variant);
begin
  Value := TGCostoPromedio.AsCurrency
end;

procedure TReportsAndForms.TGCostoPromedio_CategoriaPrint(Sender: TObject);
  Var
    V : Variant;
begin
  TGCostoPromedio_CategoriaCalc(Sender,V);
  TGCostoPromedio_Categoria.AsCurrency := V
end;

procedure TReportsAndForms.TGPrecioContado_CategoriaCalc(Sender: TObject;
  var Value: Variant);
begin
  Value := TGPrecioContado.AsCurrency
end;

procedure TReportsAndForms.TGPrecioContado_CategoriaPrint(Sender: TObject);
  Var
    V : Variant;
begin
  TGPrecioContado_CategoriaCalc(Sender,V);
  TGPrecioContado_Categoria.AsCurrency := V
end;

procedure TReportsAndForms.Total_Costo_Calc(Sender: TObject;
  var Value: Variant);
begin
  If Trim(PipeReportes.DataSource.DataSet.FieldByName('Metodo_Calculo_Costo').AsString) = 'Promedio' Then
    Value := Modulo.tReporter.FieldByName('Existencia').AsFloat *
             Modulo.tReporter.FieldByName('Costo_Promedio').AsFloat;

  If Trim(PipeReportes.DataSource.DataSet.FieldByName('Metodo_Calculo_Costo').AsString) = 'Estandar' Then
    Value := Modulo.tReporter.FieldByName('Existencia').AsFloat *
             Modulo.tReporter.FieldByName('Costo_Standar').AsFloat;

  If Trim(PipeReportes.DataSource.DataSet.FieldByName('Metodo_Calculo_Costo').AsString) = 'Última Compra' Then
    Value := Modulo.tReporter.FieldByName('Existencia').AsFloat *
             Modulo.tReporter.FieldByName('Ultimo_Precio_Compra').AsFloat;

  TCostoPromedio.AsCurrency := TCostoPromedio.AsCurrency + Value;
//  TGCostoPromedio.AsCurrency := TGCostoPromedio.AsCurrency + Value
end;

procedure TReportsAndForms.TPrecioContado_CategoriaCalc(Sender: TObject;
  var Value: Variant);
begin
  Value := TPrecioContado.AsCurrency
end;

procedure TReportsAndForms.PrecioContadoCalc(Sender: TObject;
  var Value: Variant);
begin
  Value := Modulo.tReporter.FieldByName('Existencia').AsFloat *
           Modulo.tReporter.FieldByName('Precio_Venta_Contado').AsFloat;

  TPrecioContado.AsCurrency := TPrecioContado.AsCurrency + Value;
//  TGPrecioContado.AsCurrency := TGPrecioContado.AsCurrency + Value
end;

procedure TReportsAndForms.PrecioCreditoCalc(Sender: TObject;
  var Value: Variant);
begin
  Value := Modulo.tReporter.FieldByName('Existencia').AsFloat *
           Modulo.tReporter.FieldByName('Precio_Venta_Credito').AsFloat;

//  TPrecioCredito.AsCurrency := TPrecioCredito.AsCurrency + Value;
//  TGPrecioCredito.AsCurrency := TGPrecioCredito.AsCurrency + Value
end;

procedure TReportsAndForms.PrecioMinimoCalc(Sender: TObject;
  var Value: Variant);
begin
  Value := Modulo.tReporter.FieldByName('Existencia').AsFloat *
           Modulo.tReporter.FieldByName('Precio_Venta_Minimo').AsFloat;

//  TPrecioMinimo.AsCurrency := TPrecioMinimo.AsCurrency + Value;
//  TGPrecioMinimo.AsCurrency := TGPrecioMinimo.AsCurrency + Value
end;

procedure TReportsAndForms.Print_Costo(Sender: TObject);
  Var
    txtColor : Array [False..True] Of Integer;
begin
  txtColor[False] := clWhite;
  txtColor[True] := clBlack;
  (Sender As TppCustomText).Color := txtColor[_Rep_Imprime_Costo];
  (Sender As TppCustomText).Visible := _Rep_Imprime_Costo
end;

procedure TReportsAndForms.PieGrupoAfterPrint(Sender: TObject);
begin
  TGCostoPromedio.AsCurrency := TGCostoPromedio.AsCurrency + TCostoPromedio.AsCurrency;
  TCostoPromedio.AsCurrency := 0;
  TGPrecioContado.AsCurrency := TGPrecioContado.AsCurrency + TPrecioContado.AsCurrency;
  TPrecioContado.AsCurrency := 0
end;

procedure TReportsAndForms.ppDetailBand11BeforePrint(Sender: TObject);
begin
  If Modulo.tDetalles_FacturaTotal_Precio.IsNull Then
//    Codigo.Visible := False
  Else //Codigo.Visible := True

end;

procedure TReportsAndForms.ppDetailBand15BeforePrint(Sender: TObject);
begin
  ShadeAnuladosPagosVentas.Visible := Modulo.tListadoPagosStatus.Value = _stANULADO
end;

procedure TReportsAndForms.ppDetailBand44BeforePrint(Sender: TObject);
  Var
    Jpg       : TGraphic;
    MemStream : TMemoryStream;
  Begin
    If PipeReportes.DataSource.DataSet.FieldByName('Foto').IsNull Then
      Begin
        Foto_Catalogo.Picture.LoadFromFile(_DefaultImgDir + _DefaultItemImg);
        Exit;
      End;

    Jpg := Nil;
    MemStream := TMemoryStream.Create;
    Try
      Jpg := TJpegImage.Create;
      Try
        (PipeReportes.DataSource.DataSet.FieldByName('Foto') As TBlobField).SaveToStream(MemStream);
        MemStream.Seek(0,0);
        Jpg.LoadFromStream(MemStream);
        Foto_Catalogo.Picture.Graphic:= jpg;
      Except
        Foto_Catalogo.Picture.LoadFromFile(_DefaultImgDir + _DefaultItemImg);
      End; {Try}
    Finally
      Jpg.Free;
      MemStream.Free;
    end {Try}
end;

procedure TReportsAndForms.ppDetailBand47BeforePrint(Sender: TObject);
begin
  Modulo.tFacturas.Close;
  Modulo.tFacturas.Params.ParamByName('Proceso').AsString := Modulo.tReporter.FieldByName('Proceso').AsString;
  Modulo.tFacturas.Open
end;

procedure TReportsAndForms.ppGroupHeaderBand14BeforePrint(Sender: TObject);
begin
  Cat_NombreCategoria.Caption := 'No Definido';
  If Modulo.tCategoria.Locate(Modulo.tCategoriaNumero.FieldName,
                                    Modulo.tReporter.FieldByName('Categoria').AsInteger,
                                    []) Then Cat_NombreCategoria.Caption := Modulo.tCategoriaDescripcion.Value;

  Cat_Nombre_Categoria.Caption := Cat_NombreCategoria.Caption;
  Cat_Num_Categoria.Caption := Modulo.tReporter.FieldByName('Categoria').Text
end;

procedure TReportsAndForms.ppGroupHeaderBand16BeforePrint(Sender: TObject);
begin
  Nombre_Moneda.Caption := 'N/D';
  Modulo.tFormas_Pago.Open;
  If Modulo.tFormas_Pago.Locate('Numero',Modulo.tReporter.FieldByName('Moneda').AsInteger,[]) Then
    Nombre_Moneda.Caption := Modulo.tFormas_PagoDescripcion.Value;
  Modulo.tFormas_Pago.Close
end;

procedure TReportsAndForms.ppGroupHeaderBand18BeforePrint(Sender: TObject);
begin
  Modulo.tClientes.Close;
  Modulo.tClientes.Params.ParamByName('Cedula_RNC_Pasaporte').AsString := Trim(Modulo.tReporter.FieldByName('Cliente').AsString);
  Modulo.tClientes.Open;
end;

procedure TReportsAndForms.ppGroupHeaderBand1BeforePrint(Sender: TObject);
begin
  NombreProveedor.Caption := 'No Definido';
  If Modulo.tProveedores.Locate(Modulo.tProveedoresNumero.FieldName,
                                Modulo.tReporter.FieldByName('Proveedor_Principal').AsInteger,
                                []) Then NombreProveedor.Caption := Modulo.tProveedoresNombreCompleto.Value;

 Num_Proveedor.Caption := Pad('L',Modulo.tReporter.FieldByName('Proveedor_Principal').AsString,6,'0')
end;

procedure TReportsAndForms.ppGroupHeaderBand6BeforePrint(Sender: TObject);
begin
  NombreCategoria.Caption := 'No Definido';
  Num_Categoria.Caption := Pad('L',Modulo.tReporter.FieldByName('Categoria').AsString,6,'0');
  If Modulo.tCategoria.Locate(Modulo.tCategoriaNumero.FieldName,
                                    Modulo.tReporter.FieldByName('Categoria').AsInteger,
                                    []) Then NombreCategoria.Caption := Modulo.tCategoriaDescripcion.Value;

  Nombre_Categoria.Caption := NombreCategoria.Caption
end;

procedure TReportsAndForms.ppHeaderBand11BeforePrint(Sender: TObject);
begin
  Status_Nota_Credito.Visible := Modulo.tNotas_CreditoStatus.Value <> _stACTIVO
end;

procedure TReportsAndForms.ppHeaderBand15BeforePrint(Sender: TObject);
begin
  Status_Recibo_Pago.Visible := Modulo.tPagos_ClientesStatus.Value <> _stACTIVO
end;

procedure TReportsAndForms.ppLabel282Print(Sender: TObject);
begin
  (Sender As TppLabel).Caption := RealNumToAlpha(Modulo.tNotas_CreditoMonto.Value)
end;

procedure TReportsAndForms.ppVariable11Calc(Sender: TObject;
  var Value: Variant);
begin
  Value := TPrecioContado.AsCurrency
end;

procedure TReportsAndForms.ppVariable3Calc(Sender: TObject; var Value: Variant);
begin
  Value := TGCostoPromedio.AsCurrency
end;

procedure TReportsAndForms.ppVariable5Calc(Sender: TObject; var Value: Variant);
begin
  Value := TGPrecioContado.AsCurrency
end;

procedure TReportsAndForms.ppVariable9Calc(Sender: TObject; var Value: Variant);
begin
  Value := TCostoPromedio.AsCurrency
end;

procedure TReportsAndForms.MESCalc(Sender: TObject; var Value: Variant);
begin
  Value := Copy(MesesAnio[Pipe_Criterio_Vencimiento.DataSource.DataSet.FieldByName('MES').AsInteger],1,3)
end;

procedure TReportsAndForms.UserPrint(Sender: TObject);
begin
  (Sender as TppLabel).Caption := Format('Impreso Por %s - %s',[_CurrentUser,_CurrentTerminal])
end;

procedure TReportsAndForms.ValorLetrasPrint(Sender: TObject);
begin
  (Sender As TppLabel).Caption := RealNumToAlpha(Modulo.tPagos_ClientesMonto.Value)
end;

procedure TReportsAndForms.Define_Print_Cost(Sender: TObject);
begin
  If Trim(PipeReportes.DataSource.DataSet.FieldByName('Metodo_Calculo_Costo').AsString) = 'Promedio' Then
    (Sender  As TppDBText).DataField := Modulo.tProductosCosto_Promedio.FieldName;

  If Trim(PipeReportes.DataSource.DataSet.FieldByName('Metodo_Calculo_Costo').AsString) = 'Estandar' Then
    (Sender  As TppDBText).DataField := Modulo.tProductosCosto_Standar.FieldName;

  If Trim(PipeReportes.DataSource.DataSet.FieldByName('Metodo_Calculo_Costo').AsString) = 'Última Compra' Then
    (Sender  As TppDBText).DataField := Modulo.tProductosUltimo_Precio_Compra.FieldName;

  Print_Costo(Sender)
end;

procedure TReportsAndForms.InvoiceTitleBandBeforePrint(Sender: TObject);
begin
//  InvoiceTitleBand.Visible := Ps <> 0
end;

procedure TReportsAndForms.LogoPrint(Sender: TObject);
  Var
    LogoName : String;
begin
  RegInfo.CloseKey;
  RegInfo.OpenKey(_CompanyInfoKey,False);
  LogoName := UnEncrypt(RegInfo.ReadString(_LogoName));
  Try
    (Sender As TppImage).Picture.LoadFromFile(LogoName);
  Except
     (Sender As TppImage).Visible := False
  End {Try}
end;

Initialization
  RegisterClass(TReportsAndForms);

end.
